export const publicSiteDefaults = {
  text: {
    'home.featured.eyebrow': 'Featured drop',
    'home.featured.title': '',
    'home.featured.subtitle': '',
    'home.featured.excerpt': '',
    'home.featured.readLabel': 'read',
    'home.featured.experienceLabel': 'experience',
    'home.featured.printLabel': 'print',

    'home.projects.eyebrow': 'Projects',

    'home.archive.eyebrow': 'Archive flow',
    'home.archive.title': 'Browse the archive',

    'home.filters.searchLabel': 'search',
    'home.filters.searchPlaceholder': 'title, excerpt, tag...',
    'home.filters.typeLabel': 'type',
    'home.filters.projectLabel': 'project',
    'home.filters.allLabel': 'all',
    'home.filters.loadMoreLabel': 'load more',
    'home.filters.noMatchesTitle': 'No matching pieces',
    'home.filters.noMatchesBody': 'Try changing the search or filters.',
    'home.filters.resultsPrefix': 'showing',

    'home.native.eyebrow': 'latest',
    'home.native.title': 'Latest from this publication',
    'home.native.actionLabel': 'view updates',

    'projects.hero.eyebrow': 'projects / collections / series',
    'projects.hero.title': 'Projects',
    'projects.hero.description':
      'Group related work into projects, collections, or series with their own focus and format.',
    'projects.index.eyebrow': 'Browse by project',
    'projects.index.title': 'Publishing routes',

    'projectPage.hero.eyebrow': 'project archive',
    'projectPage.hero.description': 'Archive entries grouped under this project.',
    'projectPage.featured.eyebrow': 'featured in this lane',
    'projectPage.featured.emptyTitle': 'No featured piece selected',
    'projectPage.featured.emptyBody': 'This lane is using archive fallback rules until an explicit featured piece is chosen.',
    'projectPage.featured.readLabel': 'read featured',
    'projectPage.archive.eyebrow': 'Project archive',
    'projectPage.archive.title': 'Browse pieces',
    'projectPage.filters.searchLabel': 'search',
    'projectPage.filters.searchPlaceholder': 'title, excerpt, tag...',
    'projectPage.filters.typeLabel': 'type',
    'projectPage.filters.sortLabel': 'sort',
    'projectPage.filters.allLabel': 'all',
    'projectPage.filters.newestLabel': 'newest',
    'projectPage.filters.oldestLabel': 'oldest',
    'projectPage.filters.titleLabel': 'title',
    'projectPage.filters.loadMoreLabel': 'load more',
    'projectPage.filters.noMatchesTitle': 'No matching pieces',
    'projectPage.filters.noMatchesBody': 'Try changing the search or filters.',
    'projectPage.filters.resultsPrefix': 'showing',

    'piecePage.meta.eyebrow': 'piece / archive / reading',
    'piecePage.meta.projectLabel': 'project',
    'piecePage.meta.typeLabel': 'type',
    'piecePage.meta.publishedLabel': 'published',
    'piecePage.meta.sourceLabel': 'source',
    'piecePage.meta.sourceLinkLabel': 'original post',
    'piecePage.meta.printAssetsLabel': 'print assets',
    'piecePage.meta.tagsLabel': 'tags',
    'piecePage.meta.bylinePrefix': 'by',
    'piecePage.meta.audioSummaryLabel': 'audio summary',
    'piecePage.meta.transcriptExcerptLabel': 'transcript excerpt',
    'piecePage.meta.mediaStatusLabel': 'media status',
    'piecePage.actions.readingLabel': 'reading',
    'piecePage.actions.experienceLabel': 'experience',
    'piecePage.actions.printLabel': 'print',
    'piecePage.experience.left': 'this is not a conclusion',
    'piecePage.experience.right': 'it is a beginning',
    'piecePage.nav.olderLabel': 'older',
    'piecePage.nav.newerLabel': 'newer',
    'piecePage.related.eyebrow': 'Keep going',
    'piecePage.related.title': 'Related pieces',
    'piecePage.notFound.title': 'Piece not found',
    'piecePage.notFound.body': 'This archive entry has not been imported yet or the slug changed during migration.',

    'review.hero.eyebrow': 'review / overrides / cleanup',
    'review.hero.title': 'Review Queue',
    'review.hero.description':
      'Imported pieces that probably need metadata cleanup, project reassignment, or richer handling.',
    'review.summary.projectLabel': 'by project',
    'review.summary.flagLabel': 'by flag',
    'review.filters.searchLabel': 'search',
    'review.filters.searchPlaceholder': 'title, flag, project...',
    'review.filters.flagLabel': 'flag',
    'review.filters.projectLabel': 'project',
    'review.filters.allLabel': 'all',
    'review.meta.visibleLabel': 'visible',
    'review.meta.totalFlaggedLabel': 'total flagged',
    'review.featured.label': 'featured',
    'review.featured.explicit': 'explicit feature',
    'review.featured.fallback': 'fallback feature',
    'review.featured.notFeatured': 'not featured',
    'review.overrideTools.eyebrow': 'override tools',
    'review.overrideTools.title': 'Quick Override Builder',
    'review.overrideTools.description': 'Generate override-ready snippets for common archive cleanup actions without hand-writing every object.',
    'review.overrideTools.subtitlePlaceholder': 'subtitle',
    'review.overrideTools.excerptPlaceholder': 'excerpt',
    'review.overrideTools.heroImagePlaceholder': 'hero image url',
    'review.overrideTools.projectLabel': 'project reassignment',
    'review.overrideTools.hideLabel': 'hidden',
    'review.overrideTools.featuredLabel': 'featured',
    'review.overrideTools.heroImageLabel': 'hero image',
    'review.overrideTools.audioSummaryLabel': 'audio summary',
    'review.overrideTools.transcriptLabel': 'transcript excerpt',
    'review.overrideTools.copySnippetAction': 'copy override snippet',
    'review.overrideTools.copyJsonAction': 'copy override json',
    'review.overrideTools.clearAction': 'clear builder',
    'review.overrideTools.generatedLabel': 'generated override',
    'review.overrideTools.groupByLabel': 'group by',
    'review.overrideTools.groupByProject': 'project',
    'review.overrideTools.groupByFlag': 'flag',
    'review.overrideTools.groupByNone': 'none',
    'review.overrideTools.explicitAction': 'make explicit feature',
    'review.overrideTools.unfeatureAction': 'clear featured flag',

    'podcastAdmin.eyebrow': 'podcast / transcript / bridge',
    'podcastAdmin.title': 'Podcast Enrichment',
    'podcastAdmin.description': 'Track which podcast pieces need summaries, transcript excerpts, or richer bridge metadata before native transcription lands.',
    'podcastAdmin.searchLabel': 'search',
    'podcastAdmin.searchPlaceholder': 'title, excerpt, project...',
    'podcastAdmin.statusLabel': 'status',
    'podcastAdmin.statusAll': 'all',
    'podcastAdmin.statusNeedsWork': 'needs work',
    'podcastAdmin.statusHasSummary': 'has summary',
    'podcastAdmin.statusHasTranscript': 'has transcript excerpt',
    'podcastAdmin.statusReady': 'ready',
    'podcastAdmin.visibleLabel': 'visible',
    'podcastAdmin.totalLabel': 'total podcasts',
    'podcastAdmin.missingSummaryLabel': 'missing summaries',
    'podcastAdmin.missingTranscriptLabel': 'missing transcript excerpts',
    'podcastAdmin.copyJsonAction': 'copy podcast override json',
    'podcastAdmin.copySnippetAction': 'copy podcast override snippet',
    'podcastAdmin.clearAction': 'clear builder',
    'podcastAdmin.audioSummaryLabel': 'audio summary',
    'podcastAdmin.audioSummaryPlaceholder': 'short summary for listing and detail view',
    'podcastAdmin.transcriptLabel': 'transcript excerpt',
    'podcastAdmin.transcriptPlaceholder': 'short transcript excerpt',
    'podcastAdmin.sourceNotesLabel': 'source notes',
    'podcastAdmin.sourceNotesPlaceholder': 'notes about source audio, transcript quality, or publish state',
    'podcastAdmin.heroImageLabel': 'hero image',
    'podcastAdmin.heroImagePlaceholder': 'hero image url',
    'podcastAdmin.generatedLabel': 'generated podcast override',
    'podcastAdmin.emptyTitle': 'No podcast pieces found',
    'podcastAdmin.emptyBody': 'There are currently no podcast episodes in this publication.',
    'podcastAdmin.cardStatusLabel': 'status',
    'podcastAdmin.cardNeedsWork': 'needs work',
    'podcastAdmin.cardReady': 'ready',
    'podcastAdmin.cardSummary': 'summary',
    'podcastAdmin.cardTranscript': 'transcript',
    'podcastAdmin.cardNotes': 'notes',

    'nativeBridge.eyebrow': 'native / publish / bridge',
    'nativeBridge.title': 'Native Publishing Bridge',
    'nativeBridge.description': 'Create and manage publication content directly inside SabotPress.',
    'nativeBridge.contentTypeLabel': 'content type',
    'nativeBridge.statusLabel': 'status',
    'nativeBridge.targetLabel': 'target',
    'nativeBridge.tagsLabel': 'tags',
    'nativeBridge.newEntryAction': 'new entry',
    'nativeBridge.saveEntryAction': 'save entry',
    'nativeBridge.deleteEntryAction': 'delete entry',
    'nativeBridge.duplicateEntryAction': 'duplicate entry',
    'nativeBridge.exportAction': 'copy export json',
    'nativeBridge.importAction': 'import json',
    'nativeBridge.latestHomeLabel': 'latest published home item',
    'nativeBridge.latestGeneralLabel': 'latest published general item',
    'nativeBridge.collectionLabel': 'collection',
    'nativeBridge.previewLabel': 'preview',
    'nativeBridge.emptyLabel': 'No native entries yet. Start with a note, dispatch, or publicBlock.',

    'nativeUpdates.eyebrow': 'native / updates / publishing',
    'nativeUpdates.title': 'Updates',
    'nativeUpdates.description': 'Published updates created inside this publication.',
    'nativeUpdates.emptyTitle': 'No published updates yet',
    'nativeUpdates.emptyBody': 'Native publishing exists now, but nothing has been published to the public updates surface yet.',
    'nativeUpdates.notFoundTitle': 'Update not found',
    'nativeUpdates.notFoundBody': 'That native published entry does not exist or is not publicly available.',
    'nativeUpdates.backLabel': 'back to updates',

    'admin.hero.eyebrow': 'admin / review / buildout',
    'admin.hero.title': 'Admin',
    'admin.hero.description':
      'Operational surface for writing, editing, organizing, and publishing content.',
    'admin.card.reviewEyebrow': 'review lane',
    'admin.card.reviewTitle': 'Review queue',
    'admin.card.reviewBody': 'Inspect imports that need cleanup, project reassignment, better excerpts, or richer format handling.',
    'admin.card.reviewAction': 'open review',
    'admin.card.publicConfigEyebrow': 'public config',
    'admin.card.publicConfigTitle': 'Inline public edits',
    'admin.card.publicConfigAction': 'open draft',
    'admin.card.projectEyebrow': 'project lane',
    'admin.card.projectTitle': 'Project routes',
    'admin.card.projectBody': 'Browse project groupings and verify how archive entries are organized.',
    'admin.card.projectAction': 'open projects',
    'admin.card.overrideEyebrow': 'override lane',
    'admin.card.overrideTitle': 'Override layer',
    'admin.card.overrideBody': 'Inspect manual metadata overrides used to patch imported archive entries before deeper admin editing lands.',
    'admin.card.overrideAction': 'open overrides',
    'admin.card.podcastEyebrow': 'podcast lane',
    'admin.card.podcastTitle': 'Podcast enrichment',
    'admin.card.podcastBody': 'Prepare summaries, transcript excerpts, and source notes for podcast entries before native transcription is wired in.',
    'admin.card.podcastAction': 'open podcast bridge',
    'admin.featured.globalLabel': 'global featured piece',
    'admin.featured.projectLabel': 'project featured pieces',
    'admin.featured.explicitCountLabel': 'explicit',
    'admin.featured.fallbackCountLabel': 'fallback',
    'admin.publicEditor.eyebrow': 'public editor',
    'admin.publicEditor.title': 'Public Site Config',
    'admin.publicEditor.description': 'Control the saved public-facing site configuration from the admin surface without leaving the operational workspace.',
    'admin.publicEditor.savedStatsLabel': 'saved config',
    'admin.publicEditor.draftStatsLabel': 'draft overlay',
    'admin.publicEditor.effectiveStatsLabel': 'effective config',
    'admin.publicEditor.dirtyLabel': 'dirty fields',
    'admin.publicEditor.loadLabel': 'load',
    'admin.publicEditor.saveLabel': 'save',
    'admin.publicEditor.permissionLabel': 'permission',
    'admin.publicEditor.backendLabel': 'backend',
    'admin.publicEditor.canSaveYes': 'can save',
    'admin.publicEditor.canSaveNo': 'read only',
    'admin.publicEditor.reloadAction': 'reload backend',
    'admin.publicEditor.discardAction': 'discard draft + reload',
    'admin.publicEditor.applyLocalAction': 'apply locally',
    'admin.publicEditor.saveBackendAction': 'save to backend',
    'admin.publicEditor.copyAction': 'copy changed-only payload',
    'admin.publicEditor.resetSavedAction': 'reset saved config',
    'admin.publicEditor.noDirty': 'no unsaved fields',
    'admin.publicEditor.lastLoadedLabel': 'last loaded',
    'admin.publicEditor.lastSavedLabel': 'last saved',
    'admin.workflow.eyebrow': 'editorial workflow',
    'admin.workflow.title': 'Editorial Workflow',
    'admin.workflow.description': 'Move through editing, review, media, publishing, and public verification without relying on memory.',
    'admin.workflow.step1Title': '1. Review imported archive',
    'admin.workflow.step1Body': 'Start in the review queue when a piece needs cleanup, project reassignment, excerpt repair, or feature decisions.',
    'admin.workflow.step1Action': 'open review queue',
    'admin.workflow.step2Title': '2. Patch metadata with overrides',
    'admin.workflow.step2Body': 'Use override-ready snippets when imported entries need fixes before deeper native management exists.',
    'admin.workflow.step2Action': 'open overrides',
    'admin.workflow.step3Title': '3. Enrich podcasts',
    'admin.workflow.step3Body': 'Fill summaries, transcript excerpts, and source notes for podcast entries so they present well publicly.',
    'admin.workflow.step3Action': 'open podcast bridge',
    'admin.workflow.step4Title': '4. Publish native content',
    'admin.workflow.step4Body': 'Create internal native entries for updates, dispatches, and public blocks that should render on live public routes.',
    'admin.workflow.step4Action': 'open native bridge',
    'admin.workflow.step5Title': '5. Verify public output',
    'admin.workflow.step5Body': 'Check the live updates route and homepage native highlights to confirm published content is rendering correctly.',
    'admin.workflow.step5Action': 'open public updates',
    'admin.workflow.step6Title': '6. Tune public shell',
    'admin.workflow.step6Body': 'Use public config controls when site copy, headings, and public-facing structure need adjustment.',
    'admin.workflow.step6Action': 'open public draft',

    'overrides.hero.eyebrow': 'overrides / local metadata / control layer',
    'overrides.hero.title': 'Overrides',
    'overrides.hero.description':
      'Local metadata overrides layered on top of imported archive content. This is the current manual control surface before deeper admin editing lands.',
    'overrides.meta.entryLabel': 'override entries',
    'overrides.meta.activeLabel': 'piece-overrides.json is active',
    'overrides.emptyTitle': 'No overrides yet',
    'overrides.emptyBody': 'The override layer exists, but piece-overrides.json is still empty.',

    'draft.hero.eyebrow': 'inline edit / draft / export',
    'draft.hero.title': 'Public Draft',
    'draft.hero.description':
      'Current inline edit state for the public-facing site. This page shows the saved base, the local draft delta, and the effective merged result.',
    'draft.summary.changedFieldsLabel': 'changed fields',
    'draft.summary.actionsLabel': 'actions',
    'draft.summary.emptyChanged': 'No local changes yet.',
    'draft.action.testSave': 'test save',
    'draft.action.clearDraft': 'clear local draft',
    'draft.export.savedLabel': 'saved backend/base config',
    'draft.export.effectiveLabel': 'effective merged config',
    'draft.export.changedOnlyLabel': 'changed-only payload',
    'draft.export.fullLabel': 'full payload',
    'draft.export.stateLabel': 'state',
    'draft.export.exportLabel': 'export',

    'footer.about.eyebrow': 'about',
    'footer.about.title': 'SabotPress',
    'footer.about.body':
      'Add a short description of this publication in site settings.',
    'footer.routes.eyebrow': 'routes',
    'footer.state.eyebrow': 'state',
    'footer.state.body':
      'Publication status and notes can be edited in site settings.',

    'project.harbor-rat-report.title': 'Example Project',
    'project.harbor-rat-report.description': 'Example project description. Replace or remove this project.',
    'project.the-harbor-rat-report.title': 'Example Project',
    'project.the-harbor-rat-report.description': 'Example project description. Replace or remove this project.',
    'project.molotov-now.title': 'Example Audio Project',
    'project.molotov-now.description': 'Example podcast or audio project. Replace or remove this project.',
    'project.the-communique.title': 'Example Newsletter',
    'project.the-communique.description': 'Example newsletter or recurring series. Replace or remove this project.',
    'project.black-cat-distro.title': 'Example Print Project',
    'project.black-cat-distro.description': 'Example zines, posters, and print work. Replace or remove this project.',
    'project.the-sabotuers.title': 'Example Comics Project',
    'project.the-sabotuers.description': 'Example comics and graphic storytelling project. Replace or remove this project.',
    'project.zines-and-comics.title': 'Zines and Comics',
    'project.zines-and-comics.description': 'Zines, comics, and mixed visual publishing experiments.',
  },

  styles: {},

  blocks: {
    home: {
      featured: {
        eyebrowField: 'home.featured.eyebrow',
        titleField: 'home.featured.title',
        subtitleField: 'home.featured.subtitle',
        excerptField: 'home.featured.excerpt',
        readLabelField: 'home.featured.readLabel',
        experienceLabelField: 'home.featured.experienceLabel',
        printLabelField: 'home.featured.printLabel',
      },
      projects: {
        eyebrowField: 'home.projects.eyebrow',
      },
      archive: {
        eyebrowField: 'home.archive.eyebrow',
        titleField: 'home.archive.title',
      },
      filters: {
        searchLabelField: 'home.filters.searchLabel',
        searchPlaceholderField: 'home.filters.searchPlaceholder',
        typeLabelField: 'home.filters.typeLabel',
        projectLabelField: 'home.filters.projectLabel',
        allLabelField: 'home.filters.allLabel',
        loadMoreLabelField: 'home.filters.loadMoreLabel',
        noMatchesTitleField: 'home.filters.noMatchesTitle',
        noMatchesBodyField: 'home.filters.noMatchesBody',
        resultsPrefixField: 'home.filters.resultsPrefix',
      },
    },

    projects: {
      hero: {
        eyebrowField: 'projects.hero.eyebrow',
        titleField: 'projects.hero.title',
        descriptionField: 'projects.hero.description',
      },
      index: {
        eyebrowField: 'projects.index.eyebrow',
        titleField: 'projects.index.title',
      },
    },

    projectPage: {
      hero: {
        eyebrowField: 'projectPage.hero.eyebrow',
        descriptionField: 'projectPage.hero.description',
      },
      featured: {
        eyebrowField: 'projectPage.featured.eyebrow',
        emptyTitleField: 'projectPage.featured.emptyTitle',
        emptyBodyField: 'projectPage.featured.emptyBody',
        readLabelField: 'projectPage.featured.readLabel',
      },
      archive: {
        eyebrowField: 'projectPage.archive.eyebrow',
        titleField: 'projectPage.archive.title',
      },
      filters: {
        searchLabelField: 'projectPage.filters.searchLabel',
        searchPlaceholderField: 'projectPage.filters.searchPlaceholder',
        typeLabelField: 'projectPage.filters.typeLabel',
        sortLabelField: 'projectPage.filters.sortLabel',
        allLabelField: 'projectPage.filters.allLabel',
        newestLabelField: 'projectPage.filters.newestLabel',
        oldestLabelField: 'projectPage.filters.oldestLabel',
        titleLabelField: 'projectPage.filters.titleLabel',
        loadMoreLabelField: 'projectPage.filters.loadMoreLabel',
        noMatchesTitleField: 'projectPage.filters.noMatchesTitle',
        noMatchesBodyField: 'projectPage.filters.noMatchesBody',
        resultsPrefixField: 'projectPage.filters.resultsPrefix',
      },
    },

    piecePage: {
      meta: {
        eyebrowField: 'piecePage.meta.eyebrow',
        projectLabelField: 'piecePage.meta.projectLabel',
        typeLabelField: 'piecePage.meta.typeLabel',
        publishedLabelField: 'piecePage.meta.publishedLabel',
        sourceLabelField: 'piecePage.meta.sourceLabel',
        sourceLinkLabelField: 'piecePage.meta.sourceLinkLabel',
        printAssetsLabelField: 'piecePage.meta.printAssetsLabel',
        tagsLabelField: 'piecePage.meta.tagsLabel',
        bylinePrefixField: 'piecePage.meta.bylinePrefix',
        audioSummaryLabelField: 'piecePage.meta.audioSummaryLabel',
        transcriptExcerptLabelField: 'piecePage.meta.transcriptExcerptLabel',
        mediaStatusLabelField: 'piecePage.meta.mediaStatusLabel',
      },
      actions: {
        readingLabelField: 'piecePage.actions.readingLabel',
        experienceLabelField: 'piecePage.actions.experienceLabel',
        printLabelField: 'piecePage.actions.printLabel',
      },
      experience: {
        leftField: 'piecePage.experience.left',
        rightField: 'piecePage.experience.right',
      },
      nav: {
        olderLabelField: 'piecePage.nav.olderLabel',
        newerLabelField: 'piecePage.nav.newerLabel',
      },
      related: {
        eyebrowField: 'piecePage.related.eyebrow',
        titleField: 'piecePage.related.title',
      },
      notFound: {
        titleField: 'piecePage.notFound.title',
        bodyField: 'piecePage.notFound.body',
      },
    },

    review: {
      hero: {
        eyebrowField: 'review.hero.eyebrow',
        titleField: 'review.hero.title',
        descriptionField: 'review.hero.description',
      },
      summary: {
        projectLabelField: 'review.summary.projectLabel',
        flagLabelField: 'review.summary.flagLabel',
      },
      filters: {
        searchLabelField: 'review.filters.searchLabel',
        searchPlaceholderField: 'review.filters.searchPlaceholder',
        flagLabelField: 'review.filters.flagLabel',
        projectLabelField: 'review.filters.projectLabel',
        allLabelField: 'review.filters.allLabel',
      },
      meta: {
        visibleLabelField: 'review.meta.visibleLabel',
        totalFlaggedLabelField: 'review.meta.totalFlaggedLabel',
      },
      featured: {
        labelField: 'review.featured.label',
        explicitField: 'review.featured.explicit',
        fallbackField: 'review.featured.fallback',
        notFeaturedField: 'review.featured.notFeatured',
      },
      overrideTools: {
        eyebrowField: 'review.overrideTools.eyebrow',
        titleField: 'review.overrideTools.title',
        descriptionField: 'review.overrideTools.description',
        subtitlePlaceholderField: 'review.overrideTools.subtitlePlaceholder',
        excerptPlaceholderField: 'review.overrideTools.excerptPlaceholder',
        heroImagePlaceholderField: 'review.overrideTools.heroImagePlaceholder',
        projectLabelField: 'review.overrideTools.projectLabel',
        hideLabelField: 'review.overrideTools.hideLabel',
        featuredLabelField: 'review.overrideTools.featuredLabel',
        heroImageLabelField: 'review.overrideTools.heroImageLabel',
        audioSummaryLabelField: 'review.overrideTools.audioSummaryLabel',
        transcriptLabelField: 'review.overrideTools.transcriptLabel',
        copySnippetActionField: 'review.overrideTools.copySnippetAction',
        copyJsonActionField: 'review.overrideTools.copyJsonAction',
        clearActionField: 'review.overrideTools.clearAction',
        generatedLabelField: 'review.overrideTools.generatedLabel',
        groupByLabelField: 'review.overrideTools.groupByLabel',
        groupByProjectField: 'review.overrideTools.groupByProject',
        groupByFlagField: 'review.overrideTools.groupByFlag',
        groupByNoneField: 'review.overrideTools.groupByNone',
        explicitActionField: 'review.overrideTools.explicitAction',
        unfeatureActionField: 'review.overrideTools.unfeatureAction',
      },
    },

    podcastAdmin: {
      hero: {
        eyebrowField: 'podcastAdmin.eyebrow',
        titleField: 'podcastAdmin.title',
        descriptionField: 'podcastAdmin.description',
      },
      filters: {
        searchLabelField: 'podcastAdmin.searchLabel',
        searchPlaceholderField: 'podcastAdmin.searchPlaceholder',
        statusLabelField: 'podcastAdmin.statusLabel',
        statusAllField: 'podcastAdmin.statusAll',
        statusNeedsWorkField: 'podcastAdmin.statusNeedsWork',
        statusHasSummaryField: 'podcastAdmin.statusHasSummary',
        statusHasTranscriptField: 'podcastAdmin.statusHasTranscript',
        statusReadyField: 'podcastAdmin.statusReady',
      },
      meta: {
        visibleLabelField: 'podcastAdmin.visibleLabel',
        totalLabelField: 'podcastAdmin.totalLabel',
        missingSummaryLabelField: 'podcastAdmin.missingSummaryLabel',
        missingTranscriptLabelField: 'podcastAdmin.missingTranscriptLabel',
      },
      actions: {
        copyJsonActionField: 'podcastAdmin.copyJsonAction',
        copySnippetActionField: 'podcastAdmin.copySnippetAction',
        clearActionField: 'podcastAdmin.clearAction',
      },
      builder: {
        audioSummaryLabelField: 'podcastAdmin.audioSummaryLabel',
        audioSummaryPlaceholderField: 'podcastAdmin.audioSummaryPlaceholder',
        transcriptLabelField: 'podcastAdmin.transcriptLabel',
        transcriptPlaceholderField: 'podcastAdmin.transcriptPlaceholder',
        sourceNotesLabelField: 'podcastAdmin.sourceNotesLabel',
        sourceNotesPlaceholderField: 'podcastAdmin.sourceNotesPlaceholder',
        heroImageLabelField: 'podcastAdmin.heroImageLabel',
        heroImagePlaceholderField: 'podcastAdmin.heroImagePlaceholder',
        generatedLabelField: 'podcastAdmin.generatedLabel',
      },
      empty: {
        titleField: 'podcastAdmin.emptyTitle',
        bodyField: 'podcastAdmin.emptyBody',
      },
      card: {
        statusLabelField: 'podcastAdmin.cardStatusLabel',
        needsWorkField: 'podcastAdmin.cardNeedsWork',
        readyField: 'podcastAdmin.cardReady',
        summaryField: 'podcastAdmin.cardSummary',
        transcriptField: 'podcastAdmin.cardTranscript',
        notesField: 'podcastAdmin.cardNotes',
      },
    },

    admin: {
      hero: {
        eyebrowField: 'admin.hero.eyebrow',
        titleField: 'admin.hero.title',
        descriptionField: 'admin.hero.description',
      },
      cards: {
        reviewEyebrowField: 'admin.card.reviewEyebrow',
        reviewTitleField: 'admin.card.reviewTitle',
        reviewBodyField: 'admin.card.reviewBody',
        reviewActionField: 'admin.card.reviewAction',
        publicConfigEyebrowField: 'admin.card.publicConfigEyebrow',
        publicConfigTitleField: 'admin.card.publicConfigTitle',
        publicConfigActionField: 'admin.card.publicConfigAction',
        projectEyebrowField: 'admin.card.projectEyebrow',
        projectTitleField: 'admin.card.projectTitle',
        projectBodyField: 'admin.card.projectBody',
        projectActionField: 'admin.card.projectAction',
        overrideEyebrowField: 'admin.card.overrideEyebrow',
        overrideTitleField: 'admin.card.overrideTitle',
        overrideBodyField: 'admin.card.overrideBody',
        overrideActionField: 'admin.card.overrideAction',
        podcastEyebrowField: 'admin.card.podcastEyebrow',
        podcastTitleField: 'admin.card.podcastTitle',
        podcastBodyField: 'admin.card.podcastBody',
        podcastActionField: 'admin.card.podcastAction',
      },
      featured: {
        globalLabelField: 'admin.featured.globalLabel',
        projectLabelField: 'admin.featured.projectLabel',
        explicitCountLabelField: 'admin.featured.explicitCountLabel',
        fallbackCountLabelField: 'admin.featured.fallbackCountLabel',
      },
      publicEditor: {
        eyebrowField: 'admin.publicEditor.eyebrow',
        titleField: 'admin.publicEditor.title',
        descriptionField: 'admin.publicEditor.description',
        savedStatsLabelField: 'admin.publicEditor.savedStatsLabel',
        draftStatsLabelField: 'admin.publicEditor.draftStatsLabel',
        effectiveStatsLabelField: 'admin.publicEditor.effectiveStatsLabel',
        dirtyLabelField: 'admin.publicEditor.dirtyLabel',
        loadLabelField: 'admin.publicEditor.loadLabel',
        saveLabelField: 'admin.publicEditor.saveLabel',
        permissionLabelField: 'admin.publicEditor.permissionLabel',
        backendLabelField: 'admin.publicEditor.backendLabel',
        canSaveYesField: 'admin.publicEditor.canSaveYes',
        canSaveNoField: 'admin.publicEditor.canSaveNo',
        reloadActionField: 'admin.publicEditor.reloadAction',
        discardActionField: 'admin.publicEditor.discardAction',
        applyLocalActionField: 'admin.publicEditor.applyLocalAction',
        saveBackendActionField: 'admin.publicEditor.saveBackendAction',
        copyActionField: 'admin.publicEditor.copyAction',
        resetSavedActionField: 'admin.publicEditor.resetSavedAction',
        noDirtyField: 'admin.publicEditor.noDirty',
        lastLoadedLabelField: 'admin.publicEditor.lastLoadedLabel',
        lastSavedLabelField: 'admin.publicEditor.lastSavedLabel',
      },
      workflow: {
        eyebrowField: 'admin.workflow.eyebrow',
        titleField: 'admin.workflow.title',
        descriptionField: 'admin.workflow.description',
        step1TitleField: 'admin.workflow.step1Title',
        step1BodyField: 'admin.workflow.step1Body',
        step1ActionField: 'admin.workflow.step1Action',
        step2TitleField: 'admin.workflow.step2Title',
        step2BodyField: 'admin.workflow.step2Body',
        step2ActionField: 'admin.workflow.step2Action',
        step3TitleField: 'admin.workflow.step3Title',
        step3BodyField: 'admin.workflow.step3Body',
        step3ActionField: 'admin.workflow.step3Action',
        step4TitleField: 'admin.workflow.step4Title',
        step4BodyField: 'admin.workflow.step4Body',
        step4ActionField: 'admin.workflow.step4Action',
        step5TitleField: 'admin.workflow.step5Title',
        step5BodyField: 'admin.workflow.step5Body',
        step5ActionField: 'admin.workflow.step5Action',
        step6TitleField: 'admin.workflow.step6Title',
        step6BodyField: 'admin.workflow.step6Body',
        step6ActionField: 'admin.workflow.step6Action',
      },
    },

    overrides: {
      hero: {
        eyebrowField: 'overrides.hero.eyebrow',
        titleField: 'overrides.hero.title',
        descriptionField: 'overrides.hero.description',
      },
      meta: {
        entryLabelField: 'overrides.meta.entryLabel',
        activeLabelField: 'overrides.meta.activeLabel',
      },
      empty: {
        titleField: 'overrides.emptyTitle',
        bodyField: 'overrides.emptyBody',
      },
    },

    draft: {
      hero: {
        eyebrowField: 'draft.hero.eyebrow',
        titleField: 'draft.hero.title',
        descriptionField: 'draft.hero.description',
      },
      summary: {
        changedFieldsLabelField: 'draft.summary.changedFieldsLabel',
        actionsLabelField: 'draft.summary.actionsLabel',
        emptyChangedField: 'draft.summary.emptyChanged',
      },
      actions: {
        testSaveField: 'draft.action.testSave',
        clearDraftField: 'draft.action.clearDraft',
      },
      export: {
        savedLabelField: 'draft.export.savedLabel',
        effectiveLabelField: 'draft.export.effectiveLabel',
        changedOnlyLabelField: 'draft.export.changedOnlyLabel',
        fullLabelField: 'draft.export.fullLabel',
        stateLabelField: 'draft.export.stateLabel',
        exportLabelField: 'draft.export.exportLabel',
      },
    },

    footer: {
      about: {
        eyebrowField: 'footer.about.eyebrow',
        titleField: 'footer.about.title',
        bodyField: 'footer.about.body',
      },
      routes: {
        eyebrowField: 'footer.routes.eyebrow',
      },
      state: {
        eyebrowField: 'footer.state.eyebrow',
        bodyField: 'footer.state.body',
      },
    },
  }
}
