import { useEffect, useState } from 'react'
import { createContributor, deleteCorrespondenceMessage, loadCorrespondence, patchCorrespondence, sendMessage, uploadCampaignArchiveMedia } from '../lib/campaignCorrespondenceApi'

export function CampaignCorrespondenceAdmin({ campaign, enabled = true, onNotice }) {
  const [data, setData] = useState(null)
  const [person, setPerson] = useState({ displayName: '', byline: '', pin: '', directPublish: true })
  const [createdLink, setCreatedLink] = useState('')
  const [message, setMessage] = useState('')
  const [instagram, setInstagram] = useState({ caption: '', url: '', publishedAt: '', file: null })
  const [busy, setBusy] = useState('')
  const [editingMessage, setEditingMessage] = useState(null)
  const [instagramAuth, setInstagramAuth] = useState({ status: null, link: '' })
  async function reload() { try { setData(await loadCorrespondence(campaign.slug, '', true)) } catch (error) { onNotice(`Correspondence failed to load: ${error.message}`, 'error') } }
  useEffect(() => { if (enabled) reload() }, [campaign.id, enabled])
  async function add(event) { event.preventDefault(); try { const result = await createContributor(campaign.slug, person); setCreatedLink(`${window.location.origin}/contribute/${campaign.slug}#access=${result.token}`); setPerson({ displayName: '', byline: '', pin: '', directPublish: true }); await reload(); onNotice('Contributor key created. Copy it now; the secret is not shown again.', 'success') } catch (error) { onNotice(error.message, 'error') } }
  async function revoke(item) { if (!window.confirm(`${item.revokedAt ? 'Restore' : 'Revoke'} access for ${item.displayName}?`)) return; await patchCorrespondence({ action: 'revoke', id: item.id, revoked: !item.revokedAt }); await reload() }
  async function reissue(item) { if (!window.confirm(`Replace the private link for ${item.displayName}? Their old link and any signed-in sessions will stop working. Their PIN and message history will stay the same.`)) return; setBusy(`reissue-${item.id}`); try { const result = await patchCorrespondence({ action: 'reissue', id: item.id }); setCreatedLink(`${window.location.origin}/contribute/${campaign.slug}#access=${result.token}`); await reload(); onNotice(`New private link created for ${item.displayName}. Their PIN is unchanged.`, 'success') } catch (error) { onNotice(error.message, 'error') } finally { setBusy('') } }
  async function send(event) { event.preventDefault(); if (!message.trim()) return; await sendMessage(campaign.slug, { body: message, visibility: 'private' }); setMessage(''); await reload() }
  async function importInstagram(event) { event.preventDefault(); setBusy('import'); try { const media = await uploadCampaignArchiveMedia(instagram.file); await sendMessage(campaign.slug, { body: instagram.caption, ...media, visibility: 'public', originSource: 'instagram', originId: instagramId(instagram.url), originUrl: instagram.url, originalPublishedAt: instagram.publishedAt || undefined }); setInstagram({ caption: '', url: '', publishedAt: '', file: null }); event.currentTarget.reset(); await reload(); onNotice('Instagram post archived and published.', 'success') } catch (error) { onNotice(error.message, 'error') } finally { setBusy('') } }
  async function syncInstagram() { setBusy('sync'); try { const response = await fetch('/api/campaign-instagram-sync', { method: 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ campaign: campaign.slug }) }); const result = await response.json(); if (!response.ok || !result.ok) throw new Error(result.error || 'sync failed'); await reload(); onNotice(`Instagram scan checked ${result.examined || 0} account posts: ${result.imported} imported, ${result.skipped} already archived, ${result.filtered || 0} without the campaign tag or mention.${result.errors?.length ? ` ${result.errors.length} media download errors.` : ''}`, 'success') } catch (error) { onNotice(error.message, 'error') } finally { setBusy('') } }
  async function instagramAction(action) { setBusy(`instagram-${action}`); try { const response = await fetch('/api/campaign-instagram-auth', { method: 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action, campaign: campaign.slug }) }); const result = await response.json(); if (!response.ok || !result.ok) throw new Error(result.error || 'Instagram authorization failed'); if (action === 'invite') { const link = `${window.location.origin}/campaigns/${campaign.slug}/instagram-connect#access=${result.token}`; setInstagramAuth((value) => ({ ...value, link })); await navigator.clipboard?.writeText(link); onNotice('One-use Instagram authorization link created and copied.', 'success') } else if (action === 'status') setInstagramAuth((value) => ({ ...value, status: result.status })) } catch (error) { onNotice(error.message, 'error') } finally { setBusy('') } }
  async function setQuestionStatus(item, status) { await patchCorrespondence({ action: 'question', id: item.id, status, editorNote: item.editorNote || '', messageId: item.messageId || '' }); await reload() }
  async function saveMessage(event) { event.preventDefault(); if (!editingMessage?.body.trim()) return; setBusy(`edit-${editingMessage.id}`); try { await patchCorrespondence({ action: 'message', id: editingMessage.id, body: editingMessage.body, visibility: editingMessage.visibility }); setEditingMessage(null); await reload(); onNotice('Correspondence message updated.', 'success') } catch (error) { onNotice(error.message, 'error') } finally { setBusy('') } }
  async function removeMessage(item) { const preview = item.body ? `“${item.body.slice(0, 70)}${item.body.length > 70 ? '…' : ''}”` : 'this attachment'; if (!window.confirm(`Permanently delete ${preview}? This removes it from the private room and any public dispatch feed.`)) return; setBusy(`delete-${item.id}`); try { await deleteCorrespondenceMessage(item.id); if (editingMessage?.id === item.id) setEditingMessage(null); await reload(); onNotice('Correspondence message deleted.', 'success') } catch (error) { onNotice(error.message, 'error') } finally { setBusy('') } }

  if (!enabled) return <section className="wp-meta-box campaign-correspondence-admin campaign-correspondence-admin--disabled"><div className="campaign-admin-section-header"><div><h2>Campaign Correspondence</h2><p className="description">This reusable campaign module is off. Enable “campaign correspondence and dispatches” above, save the campaign, then create contributor access and manage messages here.</p></div><span className="description">Disabled</span></div></section>

  return <section className="wp-meta-box campaign-correspondence-admin">
    <div className="campaign-admin-section-header"><div><h2>Campaign Correspondence</h2><p className="description">Private conversation, field dispatches, Instagram continuity, contributor keys, and moderated questions.</p></div><span className="description">{data?.messages?.length || 0} messages · {data?.questions?.filter((q) => q.status === 'new').length || 0} new</span></div>
    <div className="campaign-instagram-auth"><h3>Connect Instagram for automatic preservation</h3><p className="description">Create a one-use authorization link for the account owner. Sabot receives read access, never their password or permission to post to Instagram.</p><p><button className="button button--primary" type="button" disabled={Boolean(busy)} onClick={() => instagramAction('invite')}>{busy === 'instagram-invite' ? 'Creating…' : 'Create authorization link'}</button> <button className="button" type="button" disabled={Boolean(busy)} onClick={() => instagramAction('status')}>Check connection</button></p>{instagramAuth.link ? <div className="notice notice-success"><strong>Send this one-use link to Jamal</strong><input readOnly value={instagramAuth.link} onFocus={(event) => event.target.select()} /><button className="button" type="button" onClick={() => navigator.clipboard?.writeText(instagramAuth.link)}>Copy</button><p>It expires in seven days and only authorizes this campaign.</p></div> : null}{instagramAuth.status ? <p className="description">{instagramAuth.status.connected ? `Connected to @${instagramAuth.status.username || 'Instagram account'}` : 'Not connected.'}</p> : null}</div>
    <div className="campaign-instagram-import"><div><h3>Instagram continuity archive</h3><p className="description"><strong>Connected does not mean continuously scheduled yet.</strong> Use Scan connected account after publishing a Sabot post or reel containing <code>#FoodNotBombsGaza</code> or <code>@example_campaign</code>.</p><p className="description">Instagram’s native Repost button only adds an item to the Reposts tab; Meta does not return it in the connected account’s media feed. Native reposts must be archived with the manual form until they are published as actual Sabot posts or reels.</p><a className="button" href={`/contribute/${campaign.slug}?preview=1`} target="_blank" rel="noreferrer">Preview Jamal’s portal ↗</a> <button className="button button--primary" type="button" disabled={Boolean(busy)} onClick={syncInstagram}>{busy === 'sync' ? 'Scanning…' : 'Scan connected account now'}</button></div><form onSubmit={importInstagram}><label>Original post URL<input type="url" required placeholder="https://www.instagram.com/p/…" value={instagram.url} onChange={(e) => setInstagram({ ...instagram, url: e.target.value })} /></label><label>Original date<input type="datetime-local" value={instagram.publishedAt} onChange={(e) => setInstagram({ ...instagram, publishedAt: e.target.value })} /></label><label>Caption<textarea rows="5" value={instagram.caption} onChange={(e) => setInstagram({ ...instagram, caption: e.target.value })} /></label><label>Screenshot or saved video<input type="file" required accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm" onChange={(e) => setInstagram({ ...instagram, file: e.target.files?.[0] || null })} /></label><button className="button button--primary" disabled={Boolean(busy)}>{busy === 'import' ? 'Archiving…' : 'Archive and publish'}</button></form></div>
    <div className="campaign-correspondence-admin__grid"><div><h3>Contributor access</h3><form onSubmit={add} className="campaign-contributor-create"><input required placeholder="Display name" value={person.displayName} onChange={(e) => setPerson({ ...person, displayName: e.target.value })} /><input placeholder="Public byline (optional)" value={person.byline} onChange={(e) => setPerson({ ...person, byline: e.target.value })} /><input required inputMode="numeric" pattern="[0-9]{4,8}" placeholder="4–8 digit PIN" value={person.pin} onChange={(e) => setPerson({ ...person, pin: e.target.value })} /><label><input type="checkbox" checked={person.directPublish} onChange={(e) => setPerson({ ...person, directPublish: e.target.checked })} /> Can publish directly</label><button className="button button--primary">Create private link</button></form>{createdLink ? <div className="notice notice-success"><strong>Save this private link</strong><input readOnly value={createdLink} onFocus={(e) => e.target.select()} /><button type="button" className="button" onClick={() => navigator.clipboard?.writeText(createdLink)}>Copy</button><p>Bookmark it or send it now. If it is lost, use Replace private link below. The PIN and message history will remain.</p></div> : null}<div className="campaign-admin-simple-list">{data?.contributors?.map((item) => <article key={item.id}><div><strong>{item.displayName}</strong><small>{item.byline} · {item.permissions.directPublish ? 'direct publisher' : 'review only'}{item.revokedAt ? ' · revoked' : ''}</small></div><div className="campaign-contributor-actions"><button className="button" type="button" disabled={Boolean(busy)} onClick={() => reissue(item)}>{busy === `reissue-${item.id}` ? 'Replacing…' : 'Replace private link'}</button><button className="button" type="button" onClick={() => revoke(item)}>{item.revokedAt ? 'Restore' : 'Revoke'}</button></div></article>)}</div></div>
      <div><h3>Private room</h3><div className="campaign-admin-thread">{data?.messages?.map((item) => <article key={item.id} className={`is-${item.senderRole}`}>{editingMessage?.id === item.id ? <form className="campaign-admin-message-edit" onSubmit={saveMessage}><label>Message<textarea rows="4" autoFocus value={editingMessage.body} onChange={(e) => setEditingMessage({ ...editingMessage, body: e.target.value })} /></label><label>Visibility<select value={editingMessage.visibility} onChange={(e) => setEditingMessage({ ...editingMessage, visibility: e.target.value })}><option value="private">Private</option><option value="public">Public dispatch</option></select></label><div><button className="button button--primary" disabled={busy === `edit-${item.id}`}>{busy === `edit-${item.id}` ? 'Saving…' : 'Save changes'}</button><button className="button" type="button" onClick={() => setEditingMessage(null)}>Cancel</button></div></form> : <><strong>{item.displayName}</strong><p>{item.body || `[${item.mediaType} attachment]`}</p><small>{new Date(item.createdAt).toLocaleString()} · {item.visibility}{item.originSource ? ` · ${item.originSource}` : ''}</small><div className="campaign-admin-message-actions"><button className="button button-small" type="button" onClick={() => setEditingMessage({ id: item.id, body: item.body || '', visibility: item.visibility })}>Edit</button><button className="button button-small button-link-delete" type="button" disabled={busy === `delete-${item.id}`} onClick={() => removeMessage(item)}>{busy === `delete-${item.id}` ? 'Deleting…' : 'Delete'}</button></div></>}</article>)}</div><form onSubmit={send} className="campaign-admin-message"><textarea rows="3" placeholder="Ask a question or send a follow-up…" value={message} onChange={(e) => setMessage(e.target.value)} /><button className="button button--primary">Send to contributor</button></form></div></div>
    <div><h3>Public question queue</h3>{data?.questions?.length ? <div className="campaign-question-queue">{data.questions.map((item) => <article key={item.id}><div><span>{item.status}</span><strong>{item.submitterName}</strong><p>{item.question}</p></div><select value={item.status} onChange={(e) => setQuestionStatus(item, e.target.value)}>{['new','shortlisted','sent','answered','ready','published','archived'].map((status) => <option key={status}>{status}</option>)}</select></article>)}</div> : <p className="description">No public questions yet.</p>}</div>
  </section>
}
function instagramId(url) { return String(url || '').replace(/[?#].*$/, '').replace(/\/$/, '').split('/').pop() || String(url || '') }
