import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { PublicationTopbar } from './PublicationTopbar'
import { PublicationFooter } from './PublicationFooter'
import { setDocumentMeta } from '../lib/documentMeta'

const CAMPAIGN_URL = 'https://example.invalid/campaigns/example-campaign'

export function CampaignBenefitKitPage() {
  const { slug } = useParams()
  const [event, setEvent] = useState({ title: 'BENEFIT FOR FOOD NOT BOMBS GAZA', date: 'DATE + TIME', venue: 'VENUE', location: 'CITY', url: '', admission: 'SLIDING SCALE · NO ONE TURNED AWAY', details: 'MUSIC · FOOD · COMMUNITY · DIRECT AID' })
  const copy = useMemo(() => buildCopy(event), [event])
  useEffect(() => { setDocumentMeta({ title: 'Example Campaign Benefit Kit', description: 'Create downloadable benefit posters and organizing materials for Example Campaign.', canonicalPath: `/campaigns/${slug}?tool=benefit-kit` }) }, [slug])
  if (slug !== 'example-campaign') return <main><PublicationTopbar /><section className="benefit-kit-error"><h1>Toolkit unavailable</h1><Link to={`/campaigns/${slug}`}>Return to campaign</Link></section></main>
  function update(key, value) { setEvent((current) => ({ ...current, [key]: value })) }
  return <main className="benefit-kit-page"><PublicationTopbar /><header className="benefit-kit-hero"><div><p>FOOD NOT BOMBS GAZA</p><h1>Build your benefit</h1><p>Enter the details once. Download campaign-ready graphics and take the organizing materials you need.</p><Link to="/campaigns/example-campaign#benefit">← Back to campaign</Link></div></header><div className="benefit-kit-layout"><aside className="benefit-kit-fields"><h2>Event details</h2>{Object.entries(event).map(([key, value]) => <label key={key}>{fieldLabel(key)}<input value={value} onChange={(e) => update(key, e.target.value)} /></label>)}<p>Your graphics point to the permanent Sabot campaign URL, where the verified donation destination can be updated safely.</p></aside><section className="benefit-kit-workspace"><div className="benefit-kit-heading"><div><span>GRAPHICS GENERATOR</span><h2>Ready to post and print</h2></div><p>PNG downloads use the exact event details shown here.</p></div><div className="benefit-kit-previews"><GraphicPreview event={event} format="poster" /><GraphicPreview event={event} format="story" /></div><div className="benefit-kit-materials"><Material title="Event listing" text={copy.event} /><Material title="Venue pitch" text={copy.venue} /><Material title="Social caption" text={copy.social} /><Material title="Five-minute MC script" text={copy.mc} /><Material title="Press advisory" text={copy.press} /><Material title="Follow-up report" text={copy.followup} /><article><span>WORKING FILE</span><h3>Donation count sheet</h3><p>Record cash, digital donations, expenses, two-person verification, and the final amount transferred.</p><button onClick={() => downloadCsv(event)}>Download CSV</button></article><article><span>COMPLETE GUIDE</span><h3>Printable organizer guide</h3><p>Checklist, run-of-show, accessibility, safety, money handling, outreach copy, and follow-up in one styled document.</p><button onClick={() => downloadGuide(event, copy)}>Download guide</button></article></div></section></div><PublicationFooter /></main>
}

function GraphicPreview({ event, format }) { return <article className={`benefit-graphic benefit-graphic--${format}`}><div className="benefit-graphic__art" aria-hidden="true"><i /><i /><i /></div><span>DIRECT AID · DIRECT SOLIDARITY</span><h3>{event.title}</h3><div><strong>{event.date}</strong><strong>{event.venue}</strong><strong>{event.location}</strong></div><p>{event.details}</p><b>{event.admission}</b><footer><small>DONATE + DETAILS</small>{event.url ? <em>{displayUrl(event.url)}</em> : null}<strong>sabot.media/campaigns/example-campaign</strong></footer><button onClick={() => downloadGraphic(event, format)}>Download {format === 'story' ? 'story' : 'poster'} PNG</button></article> }
function Material({ title, text }) { return <article><span>READY-TO-USE COPY</span><h3>{title}</h3><p>{text}</p><button onClick={() => navigator.clipboard?.writeText(text)}>Copy</button></article> }
function fieldLabel(key) { return ({ title: 'Event title', date: 'Date and time', venue: 'Venue', location: 'City / location', url: 'Your event URL (optional)', admission: 'Admission line', details: 'Program details' })[key] || key }
function buildCopy(event) { return {
  event: `${event.title}\n${event.date} · ${event.venue} · ${event.location}\n${event.details}\n${event.admission}${event.url ? `\nEvent information: ${event.url}` : ''}\n\nWe are raising direct aid for Example Campaign, a Palestinian-led mutual-aid project preparing community meals for displaced families. SabotPress takes no percentage. Donate and learn more: ${CAMPAIGN_URL}`,
  venue: `Hi — I’m organizing ${event.title} to raise direct aid for Example Campaign. We would like to host it at your space. Could we discuss a date, capacity, accessibility, sound needs, and whether the venue can waive or reduce its fee? Campaign: ${CAMPAIGN_URL}`,
  social: `${event.title} 🍉\n\n${event.date}\n${event.venue} · ${event.location}\n${event.details}\n${event.admission}${event.url ? `\nEvent information: ${event.url}` : ''}\n\nHelp move money directly toward Palestinian-led mutual aid. Donate / details: ${CAMPAIGN_URL}`,
  mc: `Thank you for coming to ${event.title}. Tonight supports Example Campaign, a Palestinian-led mutual-aid project preparing community meals for displaced families. Donations use the verified fundraiser linked at ${CAMPAIGN_URL}. SabotPress hosts the campaign and takes no percentage. Please donate what you can, share the permanent campaign link, and help us report the total raised after the event.`,
  press: `MEDIA ADVISORY\n\nWHAT: ${event.title}\nWHEN: ${event.date}\nWHERE: ${event.venue}, ${event.location}\nWHY: A community benefit raising direct aid for Example Campaign.\nDETAILS: ${event.details}. ${event.admission}.\nCAMPAIGN: ${CAMPAIGN_URL}`,
  followup: `BENEFIT REPORT\nEvent: ${event.title}\nDate: ${event.date}\nVenue / city: ${event.venue}, ${event.location}\nAttendance: \nGross raised: \nExpenses: \nNet transferred: \nTransfer date: \nPhotos approved for publication: \nOrganizer contact: \nNotes / lessons for future organizers: `,
} }

function downloadGraphic(event, format) { const width = 1080; const height = format === 'story' ? 1920 : 1350; const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; const ctx = canvas.getContext('2d'); drawGraphic(ctx, width, height, event); const link = document.createElement('a'); link.download = `example-campaign-${format}.png`; link.href = canvas.toDataURL('image/png'); link.click() }
function drawGraphic(ctx, width, height, event) { ctx.fillStyle = '#ce1126'; ctx.fillRect(0,0,width,height); ctx.fillStyle = '#007a3d'; ctx.beginPath(); ctx.moveTo(width*.82,0); ctx.lineTo(width,0); ctx.lineTo(width,height); ctx.lineTo(width*.68,height); ctx.closePath(); ctx.fill(); ctx.fillStyle='#fff'; ctx.beginPath(); ctx.moveTo(width*.78,0); ctx.lineTo(width*.82,0); ctx.lineTo(width*.68,height); ctx.lineTo(width*.64,height); ctx.closePath(); ctx.fill(); [[.69,.12,-.6],[.62,.48,.4],[.53,.8,-.4]].forEach(([x,y,r])=>drawSeed(ctx,width*x,height*y,r)); const pad=70; ctx.fillStyle='#000'; ctx.font='900 26px Arial'; ctx.fillText('DIRECT AID · DIRECT SOLIDARITY',pad,90); ctx.fillStyle='#fff'; drawWrapped(ctx,event.title.toUpperCase(),pad,height*.19,width*.61,76,4,'900 70px Arial Black, Arial'); ctx.fillStyle='#000'; ctx.font='900 34px Arial'; let y=height*.49; [event.date,event.venue,event.location].forEach(line=>{ctx.fillText(line.toUpperCase(),pad,y);y+=48}); ctx.fillStyle='#fff'; ctx.font='700 30px Arial'; drawWrapped(ctx,event.details.toUpperCase(),pad,y+35,width*.58,40,3); ctx.fillStyle='#000'; ctx.font='900 25px Arial'; ctx.fillText(event.admission.toUpperCase(),pad,height*.78); const footerHeight=event.url?205:165; ctx.fillRect(0,height-footerHeight,width,footerHeight); ctx.fillStyle='#fff'; ctx.font='900 20px Arial'; ctx.fillText('DONATE + DETAILS',pad,height-footerHeight+48); let footerY=height-footerHeight+88; if(event.url){ctx.font='900 25px Arial';ctx.fillText(displayUrl(event.url).toUpperCase(),pad,footerY);footerY+=40} ctx.font='900 25px Arial'; ctx.fillText('SABOT.MEDIA/CAMPAIGNS/FOOD-NOT-BOMBS-GAZA',pad,footerY) }
function drawSeed(ctx,x,y,rotation){ctx.save();ctx.translate(x,y);ctx.rotate(rotation);ctx.fillStyle='#000';ctx.beginPath();ctx.moveTo(0,-20);ctx.bezierCurveTo(14,-8,13,13,0,24);ctx.bezierCurveTo(-13,13,-14,-8,0,-20);ctx.fill();ctx.restore()}
function drawWrapped(ctx,text,x,y,maxWidth,lineHeight,maxLines=Infinity,font=''){if(font)ctx.font=font;const words=text.split(/\s+/);let line='',lines=0;for(const word of words){const test=`${line}${word} `;if(ctx.measureText(test).width>maxWidth&&line){ctx.fillText(line.trim(),x,y);lines+=1;if(lines>=maxLines)return;line=`${word} `;y+=lineHeight}else line=test}if(line&&lines<maxLines)ctx.fillText(line.trim(),x,y)}
function downloadCsv(event){downloadBlob('example-campaign-donation-count.csv','text/csv',`Event,${csv(event.title)}\nDate,${csv(event.date)}\n\nType,Amount,Counted by,Verified by,Notes\nCash,,,,\nDigital,,,,\nOther,,,,\nGross total,,,,\nExpenses,,,,\nNet transferred,,,,\nTransfer date,,,,\n`)}
function downloadGuide(event,copy){const html=`<!doctype html><meta charset="utf-8"><title>Example Campaign Benefit Guide</title><style>body{font:16px Arial;max-width:850px;margin:40px auto;padding:20px;color:#111}h1{font-size:54px;line-height:.9}h2{border-top:8px solid #007a3d;padding-top:16px}pre{white-space:pre-wrap;font:15px Arial;line-height:1.5}.hero{background:#ce1126;color:#fff;padding:36px;border-right:24px solid #007a3d}li{margin:8px 0}@media print{body{margin:0}}</style><div class="hero"><small>DIRECT AID · DIRECT SOLIDARITY</small><h1>FOOD NOT BOMBS GAZA<br>BENEFIT ORGANIZER GUIDE</h1><p>${escapeHtml(event.title)} · ${escapeHtml(event.date)}</p></div><h2>Checklist</h2><ul><li>Choose an event format people will attend</li><li>Confirm an accessible venue and date</li><li>Publish the stable campaign URL everywhere</li><li>Assign door, access, money, documentation, and cleanup roles</li><li>Count funds with two people</li><li>Report the date, city, and net amount transferred</li></ul><h2>Run of show</h2><ol><li>Doors and welcome — 30 minutes</li><li>Campaign introduction — 5 minutes</li><li>Main program — 60–120 minutes</li><li>Donation reminder — 5 minutes</li><li>Announce total, thank people, and clean up</li></ol>${Object.entries(copy).map(([key,value])=>`<h2>${escapeHtml(fieldLabel(key))}</h2><pre>${escapeHtml(value)}</pre>`).join('')}<h2>Campaign</h2><p>${CAMPAIGN_URL}</p>`;downloadBlob('example-campaign-benefit-guide.html','text/html',html)}
function downloadBlob(name,type,text){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function csv(value){return `"${String(value||'').replace(/"/g,'""')}"`}
function escapeHtml(value){return String(value||'').replace(/[&<>"']/g,(char)=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' })[char])}
function displayUrl(value){return String(value||'').trim().replace(/^https?:\/\//i,'').replace(/\/$/,'').slice(0,80)}
