import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { loadCorrespondence, submitQuestion } from '../lib/campaignCorrespondenceApi'

export function CampaignDispatches({ campaign }) {
  const [state, setState] = useState({ loading: true, messages: [] })
  useEffect(() => { let live = true; loadCorrespondence(campaign.slug).then((data) => { if (live) setState({ loading: false, messages: data.messages || [] }) }).catch(() => { if (live) setState({ loading: false, messages: [] }) }); return () => { live = false } }, [campaign.slug])
  const dispatches = state.messages.filter((message) => message.originSource !== 'instagram')
  return <section className="campaign-section campaign-section--dispatches" id="dispatches"><div className="campaign-shell"><div className="campaign-section-heading"><p>DIRECT FIELD PUBLISHING</p><div><h2>{campaign.sectionTitles?.dispatches || 'Dispatches'}</h2><p>Updates published through the independent contributor portal remain available without a commercial social-media account.</p></div></div>{state.loading ? <p>Loading dispatches…</p> : dispatches.length ? <MessageList messages={dispatches} /> : <div className="campaign-dispatch-empty"><strong>The independent channel is open.</strong><p>Text, audio, video, and photographs published through the field portal will appear here.</p></div>}</div></section>
}

export function CampaignSocialArchive({ campaign }) {
  const [state, setState] = useState({ loading: true, messages: [] })
  useEffect(() => { let live = true; loadCorrespondence(campaign.slug).then((data) => { if (live) setState({ loading: false, messages: (data.messages || []).filter((message) => message.originSource === 'instagram') }) }).catch(() => { if (live) setState({ loading: false, messages: [] }) }); return () => { live = false } }, [campaign.slug])
  return <section className="campaign-section campaign-section--social-archive" id="socialArchive"><div className="campaign-shell"><div className="campaign-section-heading"><p>PLATFORM CONTINUITY</p><div><h2>{campaign.sectionTitles?.socialArchive || 'Social media archive'}</h2><p>Selected social posts are copied here with their captions, dates, source links, and independently hosted media so an Instagram takedown does not erase the record.</p></div></div>{state.loading ? <p>Loading social archive…</p> : state.messages.length ? <MessageList messages={state.messages} /> : <div className="campaign-dispatch-empty"><strong>No posts have been archived yet.</strong><p>The archive is ready. Sabot is working around Instagram’s refusal to expose the account’s native Reposts tab through its authorized media feed.</p></div>}</div></section>
}

function MessageList({ messages }) {
  return <div className="campaign-dispatch-list">{[...messages].reverse().map((message) => <article key={message.id}><header><strong>{message.displayName}</strong><time>{formatDate(message.originalPublishedAt || message.createdAt)}</time></header>{message.body ? <p>{message.body}</p> : null}<PublicMedia message={message} /><small>{message.originSource === 'instagram' ? <>Preserved from <a href={message.originUrl} target="_blank" rel="noreferrer">Instagram ↗</a></> : <>Published directly by {message.displayName}</>}</small></article>)}</div>
}

export function CampaignQuestionForm({ campaign }) {
  // SabotPress reviews submissions before anything reaches a contributor.
  const [values, setValues] = useState({ question: '', name: '', contact: '' }); const [state, setState] = useState('idle'); const [error, setError] = useState('')
  async function submit(event) { event.preventDefault(); setState('sending'); setError(''); try { await submitQuestion(campaign.slug, values); setValues({ question: '', name: '', contact: '' }); setState('sent') } catch (e) { setState('error'); setError(String(e.message || e)) } }
  return <section className="campaign-section campaign-section--questions" id="questions"><div className="campaign-shell campaign-question-layout"><div className="campaign-section-heading"><p>MODERATED PUBLIC QUESTIONS</p><div><h2>{campaign.sectionTitles?.questions || 'Ask the campaign'}</h2><p>Submit a respectful question. Sabot reviews submissions and may forward selected questions. Raw submissions are never sent directly to the contributor.</p></div></div><form onSubmit={submit}><label>Question<textarea required minLength="8" maxLength="2000" rows="5" value={values.question} onChange={(e) => setValues({ ...values, question: e.target.value })} /></label><div><label>Name or Anonymous<input maxLength="120" value={values.name} placeholder="Anonymous" onChange={(e) => setValues({ ...values, name: e.target.value })} /></label><label>Contact (optional)<input type="email" maxLength="240" value={values.contact} placeholder="Only for answer notification" onChange={(e) => setValues({ ...values, contact: e.target.value })} /></label></div><button className="campaign-button campaign-button--dark" disabled={state === 'sending'}>{state === 'sending' ? 'Sending…' : 'Submit question'}</button>{state === 'sent' ? <p role="status">Question received. Sabot will review it before anything is forwarded.</p> : null}{error ? <p role="alert">{error}</p> : null}</form></div></section>
}

export function CampaignDonation({ campaign }) {
  const donation = campaign.donation || {}; if (!donation.url) return null
  return <section className="campaign-section campaign-section--donate" id="donate"><div className="campaign-shell campaign-donation"><div><p>THE IMMEDIATE NEED</p><h2>{campaign.sectionTitles?.donate || 'Donate'}</h2><p>Food and other necessities may be available, but people need funds to obtain them under extreme and constantly changing conditions.</p></div><div className="campaign-donation__card"><span>VERIFIED DESTINATION</span><strong>{donation.recipient || campaign.shortTitle}</strong><p>{donation.explanation}</p><a className="campaign-button campaign-button--light" href={donation.url} target="_blank" rel="noreferrer">{donation.label || 'Donate'} ↗</a><small>Processed by {donation.platform || 'the named fundraiser'}, not SabotPress. Sabot takes no percentage.{donation.lastVerifiedAt ? ` Link checked ${formatDate(donation.lastVerifiedAt)}.` : ''}</small></div></div></section>
}

export function CampaignBenefitToolkit({ campaign }) {
  const campaignUrl = `https://example.invalid/campaigns/${campaign.slug}`
  const eventCopy = `We are raising direct aid for Example Campaign, a Palestinian-led mutual-aid project preparing community meals for displaced families. Donations go through the campaign’s verified fundraiser, and SabotPress takes no percentage. Learn more, hear field dispatches, and donate at ${campaignUrl}`
  const venuePitch = `Hi — I’m organizing a benefit for Example Campaign and would like to host it at your space. The event will direct people to a verified fundraiser supporting Palestinian-led community meals in Gaza. SabotPress hosts the campaign information and takes no percentage. Could we discuss a date, capacity, accessibility, sound needs, and whether the venue can waive or reduce its fee? Campaign: ${campaignUrl}`
  const socialCopy = `TURN YOUR EVENT INTO DIRECT AID 🍉\n\nWe’re organizing a benefit for Example Campaign. Come through, bring people, and help move money directly toward Palestinian-led mutual aid.\n\nDonate / details: ${campaignUrl}`
  const pack = `FOOD NOT BOMBS GAZA — BENEFIT ORGANIZER PACK\n\nCAMPAIGN\n${campaignUrl}\n\nEVENT DESCRIPTION\n${eventCopy}\n\nVENUE PITCH\n${venuePitch}\n\nSOCIAL CAPTION\n${socialCopy}\n\nCHECKLIST\n[ ] Choose a format: show, community meal, raffle, teach-in, film night, art sale, or chapter gathering\n[ ] Confirm an accessible venue and date\n[ ] Put the stable campaign URL on every listing\n[ ] State that Sabot takes no percentage\n[ ] Name who is collecting money and how it reaches the verified fundraiser\n[ ] Assign door, accessibility, money-counting, documentation, and cleanup roles\n[ ] Send the event date, city, and amount raised to SabotPress\n\nSAMPLE RUN OF SHOW\nDoors / welcome — 30 minutes\nBrief introduction to Example Campaign — 5 minutes\nProgram, meal, performances, or teach-in — 60–120 minutes\nDonation reminder and campaign link — 5 minutes\nPublic total, thanks, cleanup, and follow-up\n`
  return <section className="campaign-section campaign-section--benefit" id="benefit"><div className="campaign-shell"><div className="campaign-benefit-lead"><p>DON’T JUST SHARE IT</p><h2>{campaign.sectionTitles?.benefit || 'Organize a benefit'}</h2><p>A show, community meal, raffle, film night, art sale, teach-in, or chapter gathering can turn your local network into direct material support. Make the graphics, customize the copy, and leave with everything ready to publish.</p><div><Link className="campaign-benefit-studio-link" to={`/campaigns/${campaign.slug}/benefit-kit`}>Make posters + social graphics →</Link><button type="button" onClick={() => downloadText('example-campaign-benefit-pack.txt', pack)}>Low-bandwidth text pack</button><button type="button" onClick={() => window.print()}>Print this toolkit</button></div></div><div className="campaign-benefit-grid"><article><span>01</span><h3>Pick something your people will attend</h3><p>Use a familiar format and keep the fundraising destination clear. Small events count.</p></article><article><span>02</span><h3>Use the stable campaign link</h3><p>Put {campaignUrl} on every listing so links survive platform or fundraiser changes.</p></article><article><span>03</span><h3>Report what happened</h3><p>Send Sabot the date, city, event type, photographs you can publish, and amount raised.</p></article></div><div className="campaign-benefit-materials"><CopyCard title="Event description" text={eventCopy} label="Copy event description" /><CopyCard title="Venue outreach" text={venuePitch} label="Copy venue pitch" /><CopyCard title="Social caption" text={socialCopy} label="Copy social caption" /><article><span>EVENT CHECKLIST</span><h3>Before you announce</h3><ul><li>Accessible venue and confirmed date</li><li>Clear money-handling plan</li><li>Stable campaign link everywhere</li><li>Door, documentation, and cleanup roles</li><li>Plan to report the result</li></ul></article><article><span>SAMPLE RUN OF SHOW</span><h3>Keep it simple</h3><ol><li>Doors and welcome</li><li>Five-minute campaign introduction</li><li>Main program or meal</li><li>Donation reminder</li><li>Announce total, thank people, clean up</li></ol></article><article><span>FUNDRAISING RULE</span><h3>Make the path transparent</h3><p>Say who receives money at the event, when it will be transferred, and that the verified destination is linked through this campaign page.</p></article></div></div></section>
}
function CopyCard({ title, text, label }) { return <article><span>READY-TO-USE COPY</span><h3>{title}</h3><p>{text}</p><button type="button" onClick={() => navigator.clipboard?.writeText(text)}>{label}</button></article> }
function downloadText(filename, text) { const url = URL.createObjectURL(new Blob([text], { type: 'text/plain;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000) }
function PublicMedia({ message }) { if (!message.mediaUrl) return null; if (message.mediaType === 'audio') return <audio controls preload="metadata" src={message.mediaUrl} />; if (message.mediaType === 'video') return <video controls preload="metadata" playsInline src={message.mediaUrl} />; return <img loading="lazy" src={message.mediaUrl} alt="Field dispatch attachment" /> }
function formatDate(value) { try { return new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(value)) } catch { return value } }
