import { getPrintlabElements } from './printlabElements.js'

const stripHtml = /<[^>]*>/g
const iconPrefixes = ['lucide', 'tabler', 'ph', 'material-symbols', 'heroicons', 'feather', 'bi', 'mdi']
const iconLabels = { lucide: 'Lucide', tabler: 'Tabler Icons', ph: 'Phosphor Icons', 'material-symbols': 'Material Symbols', heroicons: 'Heroicons', feather: 'Feather Icons', bi: 'Bootstrap Icons', mdi: 'Material Design Icons' }

export const assetModeOptions = [
  { id: 'everything', label: 'Search Everything' },
  { id: 'elements', label: 'Elements' },
  { id: 'graphics', label: 'Graphics' },
  { id: 'frames', label: 'Frames' },
  { id: 'tools', label: 'Smart Tools' },
  { id: 'photos', label: 'Photos' },
  { id: 'illustrations', label: 'Illustrations' },
  { id: 'icons', label: 'Icons' },
  { id: 'historical', label: 'Historical' },
  { id: 'audio', label: 'Audio' },
  { id: 'textures', label: 'Textures' },
  { id: 'maps', label: 'Maps' },
  { id: 'documents', label: 'Documents' },
]

const conceptMap = {
  'mutual aid': ['solidarity', 'community', 'care', 'food', 'volunteer', 'hands', 'heart', 'house', 'medical', 'supplies'],
  zine: ['paper', 'photocopy', 'tape', 'staple', 'scissors', 'halftone', 'collage', 'fold', 'crop'],
  newspaper: ['press', 'article', 'dispatch', 'clipping', 'halftone'],
  radio: ['podcast', 'broadcast', 'microphone', 'audio', 'waveform', 'rss'],
  podcast: ['radio', 'broadcast', 'microphone', 'audio', 'waveform', 'rss'],
  dog: ['pet', 'animal', 'paw', 'puppy'],
  cat: ['pet', 'animal', 'paw', 'kitten'],
  food: ['meal', 'bread', 'soup', 'pantry', 'kitchen'],
  labor: ['worker', 'union', 'tools', 'factory', 'megaphone'],
  housing: ['home', 'house', 'building', 'shelter'],
  medical: ['health', 'cross', 'first aid', 'clinic'],
  map: ['location', 'pin', 'route'],
  frame: ['photo frame', 'mask', 'polaroid', 'collage'],
  splitter: ['magic splitter', 'poster split', 'tile', 'crop'],
  background: ['background remover', 'cutout', 'subject'],
  halftone: ['dots', 'print', 'texture', 'newspaper'],
}
const curatedIcons = {
  dog: ['lucide:dog', 'lucide:paw-print', 'tabler:dog', 'tabler:paw', 'mdi:dog', 'mdi:paw', 'material-symbols:pets'],
  cat: ['lucide:cat', 'lucide:paw-print', 'tabler:cat', 'tabler:paw', 'mdi:cat', 'mdi:paw', 'material-symbols:pets'],
  food: ['lucide:utensils', 'lucide:soup', 'lucide:apple', 'lucide:package', 'tabler:bowl-spoon', 'mdi:food'],
  'mutual aid': ['lucide:heart-handshake', 'lucide:hand-heart', 'lucide:users', 'lucide:house', 'lucide:package', 'lucide:utensils', 'lucide:cross', 'lucide:megaphone'],
  zine: ['lucide:scissors', 'lucide:paperclip', 'lucide:printer', 'lucide:file-text', 'lucide:copy', 'lucide:crop'],
  newspaper: ['lucide:newspaper', 'lucide:file-text', 'tabler:news', 'mdi:newspaper'],
  radio: ['lucide:radio', 'lucide:mic', 'lucide:podcast', 'lucide:rss', 'lucide:audio-lines'],
  podcast: ['lucide:podcast', 'lucide:mic', 'lucide:rss', 'lucide:audio-lines'],
  labor: ['lucide:wrench', 'lucide:hammer', 'lucide:settings', 'lucide:megaphone', 'tabler:tools'],
  housing: ['lucide:house', 'lucide:home', 'tabler:building-community', 'mdi:home'],
  medical: ['lucide:cross', 'lucide:heart-pulse', 'tabler:first-aid-kit', 'mdi:medical-bag'],
  map: ['lucide:map', 'lucide:map-pin', 'lucide:navigation', 'tabler:route'],
  frame: ['lucide:frame', 'lucide:square', 'tabler:frame'],
  splitter: ['lucide:split', 'lucide:grid-2x2', 'lucide:crop', 'tabler:crop'],
  background: ['lucide:scissors', 'lucide:image-minus', 'tabler:photo-scan'],
}
const localPackSeed = [
  ['Risograph Textures', 'textures', ['riso', 'risograph', 'texture', 'grain']],
  ['Photocopy Artifacts', 'textures', ['photocopy', 'xerox', 'noise', 'paper']],
  ['Newspaper Halftones', 'textures', ['newspaper', 'halftone', 'print', 'dot']],
]

function clean(value = '') { return String(value || '').replace(stripHtml, ' ').replace(/\s+/g, ' ').trim() }
function compactUrl(value = '') { return String(value || '').trim() }
function arr(value) { return Array.isArray(value) ? value : [] }
function unique(values = []) { const seen = new Set(); return values.map((value) => clean(value).toLowerCase()).filter((value) => value && !seen.has(value) && seen.add(value)) }
function words(value = '') { return clean(value).toLowerCase().split(/[^a-z0-9]+/).filter((word) => word.length > 1) }
function keyFor(query = '') { const q = clean(query).toLowerCase(); return Object.keys(conceptMap).find((key) => q === key || q.includes(key)) || '' }
function termsFor(query = '') { const q = clean(query); return unique([q, ...words(q).filter((word) => word.length > 2), ...(conceptMap[keyFor(q)] || [])]) }
function titleCase(value = '') { return clean(value).replace(/[-_]+/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()) }
function textOf(asset) { return [asset.title, asset.description, asset.category, asset.bucket, asset.sourceLabel, ...(asset.tags || [])].join(' ').toLowerCase() }
function iconParts(icon = '') { const [prefix = '', name = ''] = clean(icon).split(':'); return { prefix, name } }
function iconBucket(name = '') { const text = clean(name).toLowerCase(); if (/arrow|chevron|direction/.test(text)) return 'arrows'; if (/frame|mask|square|circle/.test(text)) return 'frames'; if (/radio|mic|podcast|rss|audio|wave/.test(text)) return 'media'; if (/newspaper|article|file|document|book/.test(text)) return 'editorial'; return 'icons' }

export function expandEditorialQuery(query = '') { return termsFor(query) }
export function expandElementQuery(query = '') { return termsFor(query) }
function mediaTypeFor(input = {}) { const mediaType = clean(input.mediaType || input.type || '').toLowerCase(); const mimeType = clean(input.mimeType || input.mime || '').toLowerCase(); const url = compactUrl(input.downloadUrl || input.previewUrl || input.thumbnailUrl || input.fullUrl || input.url); if (mediaType) return mediaType; if (mimeType.includes('svg') || /\.svg($|\?)/i.test(url)) return 'icon'; if (mimeType.startsWith('audio/')) return 'audio'; if (mimeType.includes('pdf') || /\.(pdf|docx?|txt)($|\?)/i.test(url)) return 'document'; return 'image' }
export function normalizePrintlabAsset(asset) { if (!asset || typeof asset !== 'object') return null; const downloadUrl = compactUrl(asset.downloadUrl || asset.fullUrl || asset.url || asset.previewUrl || asset.thumbnailUrl); const previewUrl = compactUrl(asset.previewUrl || asset.thumbnailUrl || downloadUrl); const thumbnailUrl = compactUrl(asset.thumbnailUrl || previewUrl || downloadUrl); const landingPageUrl = compactUrl(asset.landingPageUrl || asset.landingUrl || asset.foreignLandingUrl || ''); if (!downloadUrl && !previewUrl && !thumbnailUrl && !landingPageUrl) return null; const source = clean(asset.source || asset.originalProvider || 'external'); const sourceLabel = clean(asset.sourceLabel || asset.providerLabel || source || 'External'); const title = clean(asset.title || 'Untitled asset'); const creator = clean(asset.creator || ''); const license = clean(asset.license || ''); const licenseUrl = compactUrl(asset.licenseUrl || ''); const attributionText = clean(asset.attributionText || asset.attribution || [title, creator ? `by ${creator}` : '', sourceLabel, license].filter(Boolean).join(' / ')); const width = Number(asset.width); const height = Number(asset.height); const normalized = { id: String(asset.id || asset.originalId || `${source}:${downloadUrl || previewUrl || thumbnailUrl || landingPageUrl}`), title, creator, description: clean(asset.description || asset.caption || ''), thumbnailUrl, previewUrl, downloadUrl, landingPageUrl, license, licenseUrl, source, sourceLabel, mediaType: mediaTypeFor(asset), width: Number.isFinite(width) && width > 0 ? width : null, height: Number.isFinite(height) && height > 0 ? height : null, mimeType: clean(asset.mimeType || asset.mime || ''), attributionText, tags: unique(arr(asset.tags).length ? asset.tags : String(asset.tags || '').split(',')), category: clean(asset.category || ''), bucket: clean(asset.bucket || asset.category || ''), raw: asset.raw ?? asset, originalProvider: clean(asset.originalProvider || source), originalId: String(asset.originalId || asset.id || '') }; return { ...normalized, fullUrl: normalized.downloadUrl, url: normalized.downloadUrl, sourceName: normalized.sourceLabel, landingUrl: normalized.landingPageUrl, attribution: normalized.attributionText } }
function normalizeLocalMedia(item) { return normalizePrintlabAsset({ id: item?.id, title: item?.title || item?.filename || 'Uploaded media', thumbnailUrl: item?.thumbnailUrl || item?.url || item?.dataUrl, previewUrl: item?.previewUrl || item?.url || item?.dataUrl, downloadUrl: item?.downloadUrl || item?.fullUrl || item?.url || item?.dataUrl, source: 'local-media', sourceLabel: 'SabotPress Library', creator: item?.creator || '', license: item?.license || '', licenseUrl: item?.licenseUrl || '', attributionText: item?.attributionText || item?.attribution || item?.caption || '', mediaType: item?.mediaType || 'image', tags: item?.tags || [], raw: item }) }
function normalizeIconify(input) { const icon = typeof input === 'string' ? input : input.icon; const { prefix, name } = iconParts(icon); if (!prefix || !name) return null; const svgUrl = `https://api.iconify.design/${encodeURIComponent(prefix)}/${encodeURIComponent(name)}.svg`; const label = iconLabels[prefix] || prefix; return normalizePrintlabAsset({ id: `iconify:${icon}`, originalProvider: 'iconify', originalId: icon, title: titleCase(name.replace(/^ic-/, '').replace(/-\d+$/, '')), thumbnailUrl: svgUrl, previewUrl: svgUrl, downloadUrl: svgUrl, source: 'iconify', sourceLabel: `Iconify / ${label}`, creator: prefix, license: 'Icon set license varies', licenseUrl: 'https://iconify.design/docs/icons/license.html', attributionText: `${icon} icon from Iconify. Verify the ${label} license before publication.`, mediaType: 'icon', mimeType: 'image/svg+xml', landingPageUrl: `https://icon-sets.iconify.design/${encodeURIComponent(prefix)}/${encodeURIComponent(name)}/`, tags: [prefix, label, name, ...words(name), ...(input.tags || []), 'svg', 'icon', 'vector'], category: 'Icons', bucket: iconBucket(name), raw: input }) }
function normalizeOpenverse(item, tags = []) { const title = clean(item?.title || 'Untitled'); const creator = clean(item?.creator || ''); const license = clean(item?.license || ''); return normalizePrintlabAsset({ id: `openverse:${item?.id || item?.url || ''}`, originalProvider: 'openverse', originalId: item?.id || item?.url || '', title, thumbnailUrl: item?.thumbnail || item?.url, previewUrl: item?.thumbnail || item?.url, downloadUrl: item?.url || item?.thumbnail, source: 'openverse', sourceLabel: item?.source ? `Openverse / ${item.source}` : 'Openverse', creator, license, licenseUrl: item?.license_url, attributionText: clean(item?.attribution || [title, creator ? `by ${creator}` : '', license].filter(Boolean).join(' / ')), mediaType: 'graphic', landingPageUrl: item?.foreign_landing_url, width: item?.width, height: item?.height, tags: [title, creator, item?.source, ...tags], category: 'Open Graphics', bucket: 'graphics', raw: item }) }
function normalizeCommons(page, tags = []) { const info = page?.imageinfo?.[0] || {}; const title = clean(info?.extmetadata?.ObjectName?.value || page?.title || '').replace(/^File:/, ''); return normalizePrintlabAsset({ id: `wikimedia:${page.pageid || info.url}`, originalProvider: 'wikimedia', originalId: page.pageid || info.url || '', title, thumbnailUrl: info.thumburl || info.url, previewUrl: info.thumburl || info.url, downloadUrl: info.url || info.thumburl, source: 'wikimedia', sourceLabel: 'Wikimedia Commons', creator: clean(info.user || ''), license: clean(info?.extmetadata?.LicenseShortName?.value || ''), licenseUrl: compactUrl(info?.extmetadata?.LicenseUrl?.value || ''), attributionText: [title, info.user, 'Wikimedia Commons'].filter(Boolean).join(' / '), mediaType: String(info.mime || '').includes('svg') ? 'graphic' : 'photo', landingPageUrl: info.descriptionurl, mimeType: info.mime, width: info.width, height: info.height, tags: ['commons', 'historical', title, ...tags], category: 'Open Graphics', bucket: 'graphics', raw: page }) }
function normalizeLocalPack([title, mode, tags], index) { const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="420" viewBox="0 0 640 420"><rect width="640" height="420" fill="#f6f1e8"/><rect x="34" y="34" width="572" height="352" fill="none" stroke="#1d2327" stroke-width="12"/></svg>`; const url = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`; return normalizePrintlabAsset({ id: `local-pack:${index}`, title, thumbnailUrl: url, previewUrl: url, downloadUrl: url, source: 'local-packs', sourceLabel: 'Local Asset Packs', creator: 'SabotPress', license: 'Internal curated asset', attributionText: `${title} local pack / SabotPress`, mediaType: mode, mimeType: 'image/svg+xml', tags, bucket: mode, raw: { title, mode, tags } }) }
async function fetchJson(url) { const res = await fetch(url, { headers: { accept: 'application/json' } }); const data = await res.json().catch(() => null); if (!res.ok) throw new Error(data?.detail || data?.error || `Search failed: ${res.status}`); if (!data || typeof data !== 'object') throw new Error('Search returned an unreadable response.'); return data }
async function searchIconifyTerm(term, limit = 36) { const url = new URL('https://api.iconify.design/search'); url.searchParams.set('query', term); url.searchParams.set('limit', String(limit)); const data = await fetchJson(url); return arr(data.icons).filter((icon) => iconPrefixes.includes(iconParts(icon).prefix)) }
async function searchIconify(query, expandedTerms = []) { const q = clean(query); const key = keyFor(q); const terms = unique([q, ...termsFor(q), ...expandedTerms]); const seen = new Set(); const icons = []; (curatedIcons[key] || []).forEach((icon) => { seen.add(icon); icons.push({ icon, tags: terms }) }); let firstError = null; for (const term of terms.slice(0, 5)) { try { (await searchIconifyTerm(term)).forEach((icon) => { if (!seen.has(icon)) { seen.add(icon); icons.push({ icon, tags: [term] }) } }) } catch (err) { if (!firstError) firstError = err } } if (!icons.length && firstError) throw firstError; const counts = new Map(); return icons.filter((item) => { const { prefix, name } = iconParts(item.icon); const count = counts.get(prefix) || 0; if (count >= 3) return false; if (!/arrow|line|direction|divider/i.test(q) && /arrow|chevron/.test(name)) return false; counts.set(prefix, count + 1); return true }).slice(0, 30) }
function externalQueries(query, mode = 'everything') { const q = clean(query); const terms = termsFor(q); if (mode === 'frames') return unique([`${q} frame`, 'polaroid frame', 'torn paper frame', 'photo collage frame']).slice(0, 4); if (mode === 'textures') return unique([`${q} texture`, 'photocopy texture', 'halftone texture']).slice(0, 4); if (['elements', 'graphics', 'illustrations'].includes(mode)) return unique([`${q} illustration`, `${q} graphic`, `${q} collage`, ...terms.map((term) => `${term} illustration`)]).slice(0, 5); return unique([q, ...terms]).slice(0, 3) }
async function searchOpenverse({ query, mode, expandedTerms }) { const settled = await Promise.all(externalQueries(query, mode).map(async (term) => { const url = new URL('https://api.openverse.org/v1/images/'); url.searchParams.set('q', term); url.searchParams.set('page_size', ['elements', 'graphics'].includes(mode) ? '10' : '16'); const data = await fetchJson(url); return arr(data.results).map((item) => normalizeOpenverse(item, [query, term, ...expandedTerms])) })); return settled.flat() }
async function searchWikimedia({ query, mode, expandedTerms }) { const settled = await Promise.all(externalQueries(query, mode).slice(0, 2).map(async (term) => { const url = new URL('https://commons.wikimedia.org/w/api.php'); url.searchParams.set('action', 'query'); url.searchParams.set('format', 'json'); url.searchParams.set('origin', '*'); url.searchParams.set('generator', 'search'); url.searchParams.set('gsrnamespace', '6'); url.searchParams.set('gsrlimit', '10'); url.searchParams.set('gsrsearch', term); url.searchParams.set('prop', 'imageinfo'); url.searchParams.set('iiprop', 'url|extmetadata|mime|user|size'); url.searchParams.set('iiurlwidth', '420'); const data = await fetchJson(url); const pages = data.query?.pages && typeof data.query.pages === 'object' ? Object.values(data.query.pages) : []; return pages.map((page) => normalizeCommons(page, [query, term, ...expandedTerms])) })); return settled.flat() }
function modeMatches(asset, mode) { if (!asset || mode === 'everything') return true; const mediaType = clean(asset.mediaType).toLowerCase(); const text = textOf(asset); if (mode === 'elements') return ['printlab-elements', 'openverse', 'wikimedia', 'iconify'].includes(asset.source) || ['element', 'graphic', 'photo', 'image', 'icon', 'texture'].includes(mediaType); if (mode === 'graphics') return ['openverse', 'wikimedia', 'printlab-elements'].includes(asset.source) || ['graphic', 'illustration', 'element'].includes(mediaType); if (mode === 'frames') return text.includes('frame') || text.includes('mask') || asset.bucket === 'frame'; if (mode === 'tools') return asset.bucket === 'tool' || text.includes('tool') || text.includes('splitter') || text.includes('background'); if (mode === 'photos') return ['photo', 'image'].includes(mediaType) || (mediaType === 'image' && asset.source !== 'iconify'); if (mode === 'illustrations') return ['illustration', 'graphic', 'element'].includes(mediaType) || text.includes('graphic'); if (mode === 'icons') return mediaType === 'icon' || asset.source === 'iconify'; if (mode === 'historical') return asset.source === 'wikimedia' || text.includes('historical'); if (mode === 'audio') return mediaType === 'audio'; if (mode === 'textures') return mediaType === 'texture' || ['texture', 'riso', 'photocopy', 'halftone', 'stain', 'fold', 'overlay'].some((term) => text.includes(term)); if (mode === 'maps') return mediaType === 'map' || text.includes('map'); if (mode === 'documents') return mediaType === 'document' || text.includes('document'); return true }
function textMatches(asset, terms) { return !terms.length || terms.some((term) => textOf(asset).includes(term)) }
function rank(asset, query, terms, mode) { const text = textOf(asset); const title = clean(asset.title).toLowerCase(); const exact = clean(query).toLowerCase(); let score = 0; if (asset.source === 'openverse' || asset.source === 'wikimedia') score += ['elements', 'graphics'].includes(mode) ? 320 : 120; if (asset.source === 'printlab-elements') score += ['elements', 'frames', 'textures', 'tools'].includes(mode) ? 270 : 130; if (asset.source === 'iconify') score += mode === 'icons' ? 220 : mode === 'elements' ? 80 : 50; if (asset.source === 'local-media') score += 180; if (asset.source === 'local-packs') score += mode === 'elements' ? -220 : 20; if (exact && title.includes(exact)) score += 90; score += Math.min(150, terms.filter((term) => text.includes(term)).length * 18); if (asset.bucket === 'frame' && ['elements', 'frames'].includes(mode)) score += 180; if (asset.bucket === 'texture' && ['elements', 'textures', 'graphics'].includes(mode)) score += 150; if (asset.bucket === 'tool' && ['elements', 'tools'].includes(mode)) score += 280; if (!/arrow|line|direction|divider/i.test(exact) && /arrow|chevron/.test(text)) score -= 260; return score }
function dedupe(items) { const seen = new Set(); return items.filter((asset) => { const key = asset?.id || asset?.downloadUrl || asset?.previewUrl; if (!key || seen.has(key)) return false; seen.add(key); return true }) }
function diversify(items, query) { const q = clean(query).toLowerCase(); const counts = new Map(); const first = []; const later = []; for (const asset of items) { const key = asset.source === 'iconify' ? asset.creator : asset.source; const count = counts.get(key) || 0; if (first.length < 48 && key === 'iconify' && count >= 3) { later.push(asset); continue } if (first.length < 48 && !/arrow|line|direction|divider/i.test(q) && asset.bucket === 'arrows') { later.push(asset); continue } counts.set(key, count + 1); first.push(asset) } return [...first, ...later] }
const providers = [
  { id: 'printlab-elements', label: 'Printlab Elements', modes: ['everything', 'elements', 'graphics', 'frames', 'tools', 'illustrations', 'textures', 'maps', 'documents'], async search({ query, expandedTerms, mode }) { const terms = mode === 'elements' ? expandElementQuery(query) : expandedTerms.length ? expandedTerms : expandEditorialQuery(query); return getPrintlabElements().map(normalizePrintlabAsset).filter(Boolean).filter((asset) => modeMatches(asset, mode)).filter((asset) => textMatches(asset, terms)) } },
  { id: 'openverse', label: 'Openverse', modes: ['everything', 'elements', 'graphics', 'photos', 'illustrations', 'textures', 'frames'], async search({ query, mode, expandedTerms }) { if (!query) return []; return searchOpenverse({ query, mode, expandedTerms }) } },
  { id: 'wikimedia', label: 'Wikimedia Commons', modes: ['everything', 'elements', 'graphics', 'photos', 'illustrations', 'historical', 'maps', 'documents', 'frames'], async search({ query, mode, expandedTerms }) { if (!query) return []; return searchWikimedia({ query, mode, expandedTerms }) } },
  { id: 'iconify', label: 'Iconify', modes: ['everything', 'elements', 'icons'], async search({ query, expandedTerms }) { if (!query) return []; return (await searchIconify(query, expandedTerms)).map(normalizeIconify).filter(Boolean) } },
  { id: 'local-media', label: 'SabotPress Library', modes: ['everything', 'elements', 'graphics', 'photos', 'illustrations', 'icons', 'audio', 'textures', 'maps', 'documents', 'frames'], async search({ query, expandedTerms, mode, localMedia }) { const terms = expandedTerms.length ? expandedTerms : expandEditorialQuery(query); return arr(localMedia).map(normalizeLocalMedia).filter(Boolean).filter((asset) => modeMatches(asset, mode)).filter((asset) => textMatches(asset, terms)) } },
  { id: 'local-packs', label: 'Local Asset Packs', modes: ['everything', 'illustrations', 'historical', 'textures', 'documents'], async search({ query, expandedTerms, mode }) { const terms = expandedTerms.length ? expandedTerms : expandEditorialQuery(query); return localPackSeed.map(normalizeLocalPack).filter(Boolean).filter((asset) => modeMatches(asset, mode)).filter((asset) => textMatches(asset, terms)) } },
]
export const assetProviders = providers.map(({ id, label, modes }) => ({ id, label, modes }))
function effectiveSources(sourceIds = [], mode = 'everything') { if (mode !== 'elements' || !sourceIds.length) return sourceIds; return sourceIds.includes('printlab-elements') && !sourceIds.some((id) => ['openverse', 'wikimedia', 'iconify'].includes(id)) ? [] : sourceIds }
export async function searchUnifiedAssets({ query, mode = 'everything', sourceIds = [], localMedia = [] } = {}) { const cleanQuery = clean(query); const expandedTerms = mode === 'elements' ? expandElementQuery(cleanQuery) : expandEditorialQuery(cleanQuery); const activeSources = effectiveSources(sourceIds, mode); const activeProviders = providers.filter((provider) => (!activeSources.length || activeSources.includes(provider.id)) && (mode === 'everything' || provider.modes.includes(mode))); const settled = await Promise.all(activeProviders.map(async (provider) => { try { return { provider: { id: provider.id, label: provider.label }, results: arr(await provider.search({ query: cleanQuery, expandedTerms, mode, localMedia })).map(normalizePrintlabAsset).filter(Boolean), error: '' } } catch (err) { return { provider: { id: provider.id, label: provider.label }, results: [], error: String(err?.message || err || 'Provider failed.') } } })); const results = diversify(dedupe(settled.flatMap((entry) => entry.results)).filter((asset) => modeMatches(asset, mode)).filter((asset) => textMatches(asset, expandedTerms)).map((asset) => ({ ...asset, rank: rank(asset, cleanQuery, expandedTerms, mode) })).sort((a, b) => b.rank - a.rank || a.title.localeCompare(b.title)), cleanQuery); return { results, providers: settled.map((entry) => ({ id: entry.provider.id, label: entry.provider.label, count: entry.results.length, error: entry.error, state: entry.error ? 'error' : 'loaded' })), expandedTerms } }
export function importUrlAsset(rawUrl) { const downloadUrl = compactUrl(rawUrl); if (!downloadUrl) return null; let parsed = null; try { parsed = new URL(downloadUrl) } catch { throw new Error('Enter a valid URL.') } const filename = decodeURIComponent(parsed.pathname.split('/').pop() || '').replace(/\.[^.]+$/, ''); return normalizePrintlabAsset({ id: `url:${downloadUrl}`, originalProvider: 'url-import', originalId: downloadUrl, title: filename || parsed.hostname || 'URL import', thumbnailUrl: downloadUrl, previewUrl: downloadUrl, downloadUrl, source: 'url-import', sourceLabel: 'URL Import', creator: parsed.hostname, license: 'Unknown', attributionText: `Imported from ${parsed.hostname}. Add creator/license metadata before publication.`, mediaType: /\.svg($|\?)/i.test(parsed.pathname) ? 'icon' : 'image', landingPageUrl: downloadUrl }) }
export async function searchAssetSource(sourceId, query, options = {}) { const data = await searchUnifiedAssets({ query, mode: options.mode || 'everything', sourceIds: [sourceId], localMedia: options.localMedia || [] }); const providerState = data.providers.find((provider) => provider.id === sourceId); if (providerState?.error) throw new Error(providerState.error); return data.results }
