import React from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App'
import { PublicAccessibilityGate } from './components/PublicAccessibilityGate'
import './styles.css'
import './public-mobile.css'
import './public-admin-toolbar-fix.css'
import './public-masthead-fit.css'
import './public-preview-media-layout.css'
import './public-archive-polish.css'
import './admin-polish.css'
import './sabotpress-setup.css'
import './admin-analytics.css'
import './admin-editor-form-fix.css'
import './admin-editor-link-tools.css'
import './admin-classic-editor-toolbar.css'
import './admin-classic-editor-polish.css'
import './admin-editor-usability.css'
import './admin-editor-focus-mode-fix.css'
import './printlab-disabled-tools.css'
import './audio-lab.css'
import './audio-lab-recording.css'
import './audio-lab-phase4.css'
import './audio-lab-phase5.css'
import './audio-lab-phase6.css'
import './audio-lab-phase7.css'
import './audio-lab-phase8.css'
import './audio-lab-fullscreen.css'
import './audio-lab-workspace.css'
import './audio-lab-workspace-final.css'
import './audio-lab-waveform-focus.css'
import './audio-lab-professional-polish.css'
import './audio-lab-task-pages.css'
import './audio-lab-transcription.css'
import './audio-lab-direct-manipulation.css'
import './audio-lab-shortcuts.css'
import './admin-media-library.css'
import './admin-users.css'
import './public-reading-type-fix.css'
import './public-type-force.css'
import './public-featured-image-only.css'
import './public-translation-selector.css'
import './admin-navigation.css'
import './admin-public-config.css'
import './sitewide-mobile-polish.css'
import './public-card-title-fit.css'
import './public-card-overlay-v2.css'
import './home-feed-v3.css'
import './campaign-page.css'
import './campaign-page-polish.css'
import './campaign-coverage-archive.css'
import './campaign-correspondence.css'
import './campaign-benefit-kit.css'
import './instagram-connect.css'
import './contact-secure-form.css'
import './admin-editor-sticky-toolbar.css'
import './public-accessibility.css'
/* Authoritative AudioLab workspace layers. */
import './audio-lab-audacity-layout.css'
import './audio-lab-studio-v4.css'
/* A cold Studio popup first requests /?audiolab-studio=1. This module rewrites
   that guaranteed root document to the real protected AudioLab route before
   every route-aware AudioLab runtime below evaluates. */
import './audioLabStandalone.js'
/* Own audio-file change events before the legacy React importer so source files
   are preserved first and unsupported decodes produce visible feedback. */
import './audioLabImportReliability.js'
import './audioLabKeyboardShortcuts.js'
import './audioLabTaskPages.js'
import './audioLabTaskNavigationFix.js'
import './audioLabBestTranscriptionResume.js'
import './audioLabLocalTranscription.js'
import './adminFileMediaInsert.js'
import './adminEditorLinkTools.js'
import './adminClassicEditorToolbar.js'
import './adminClassicEditorPolish.js'
import './adminNativePreviewFix.js'
import './publicPreviewMediaLayout.js'
import './publicArchiveCleanup.js'
import './publicTypeRuntimeFix.js'
import './publicTranslationSelector.js'
import './audioLabDirectManipulation.js'
import './audioLabAudacityParity.js'
import './audioLabFliteVoice.js'
import './audioLabWorkspaceV2.js'
/* Final AudioLab layer: menus, visible tracks, standard Audacity spatial hierarchy. */
import './audio-lab-audacity-v5.css'
import './audio-lab-audacity-tools.css'
import './audio-lab-dialog-track-focus.css'
import './audio-lab-standalone.css'
import './audioLabAudacityMenu.js'
import './audioLabAudacityQuickTools.js'
/* React Router uses pushState, which does not emit popstate. This bridge makes
   all route-aware AudioLab enhancements initialize when the page is entered
   through normal SPA admin navigation instead of requiring a hard refresh. */
import './audioLabSpaRuntimeGuard.js'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
      <PublicAccessibilityGate />
    </BrowserRouter>
  </React.StrictMode>,
)
