const encoder = new TextEncoder()
const decoder = new TextDecoder()

export async function ensureInstagramTables(db) {
  for (const sql of [
    `CREATE TABLE IF NOT EXISTS campaign_instagram_invites (id TEXT PRIMARY KEY, campaign_id TEXT NOT NULL, token_hash TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, used_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS campaign_instagram_oauth_states (state_hash TEXT PRIMARY KEY, invite_id TEXT NOT NULL, campaign_id TEXT NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS campaign_instagram_connections (campaign_id TEXT PRIMARY KEY, instagram_user_id TEXT NOT NULL, username TEXT NOT NULL DEFAULT '', access_token_encrypted TEXT NOT NULL, token_expires_at TEXT, connected_at TEXT NOT NULL, updated_at TEXT NOT NULL, revoked_at TEXT)`,
  ]) await db.prepare(sql).run()
}
export async function createInstagramInvite(db, campaignId) { await ensureInstagramTables(db); const id=crypto.randomUUID(),token=randomSecret(32),expiresAt=new Date(Date.now()+7*86400000).toISOString(); await db.prepare(`INSERT INTO campaign_instagram_invites (id,campaign_id,token_hash,expires_at) VALUES (?,?,?,?)`).bind(id,campaignId,await sha256(token),expiresAt).run(); return {token,expiresAt} }
export async function consumeInstagramInvite(db,campaignId,token){await ensureInstagramTables(db);const now=new Date().toISOString();const row=await db.prepare(`SELECT * FROM campaign_instagram_invites WHERE campaign_id=? AND token_hash=? AND used_at IS NULL AND datetime(expires_at)>datetime(?) LIMIT 1`).bind(campaignId,await sha256(token),now).first();if(!row)throw new Error('This Instagram authorization link is invalid, expired, or already used.');const state=randomSecret(32),expiresAt=new Date(Date.now()+15*60000).toISOString();await db.prepare(`INSERT INTO campaign_instagram_oauth_states (state_hash,invite_id,campaign_id,expires_at) VALUES (?,?,?,?)`).bind(await sha256(state),row.id,campaignId,expiresAt).run();return{state}}
export async function consumeOAuthState(db,state){await ensureInstagramTables(db);const now=new Date().toISOString();const row=await db.prepare(`SELECT * FROM campaign_instagram_oauth_states WHERE state_hash=? AND datetime(expires_at)>datetime(?) LIMIT 1`).bind(await sha256(state),now).first();if(!row)throw new Error('Instagram authorization expired. Ask SabotPress for a new link.');await db.prepare('DELETE FROM campaign_instagram_oauth_states WHERE state_hash=?').bind(row.state_hash).run();await db.prepare('UPDATE campaign_instagram_invites SET used_at=? WHERE id=?').bind(now,row.invite_id).run();return row}
export async function saveInstagramConnection(db,campaignId,profile,token,expiresAt,secret){const now=new Date().toISOString(),encrypted=await encryptToken(token,secret);await db.prepare(`INSERT INTO campaign_instagram_connections (campaign_id,instagram_user_id,username,access_token_encrypted,token_expires_at,connected_at,updated_at,revoked_at) VALUES (?,?,?,?,?,?,?,NULL) ON CONFLICT(campaign_id) DO UPDATE SET instagram_user_id=excluded.instagram_user_id,username=excluded.username,access_token_encrypted=excluded.access_token_encrypted,token_expires_at=excluded.token_expires_at,updated_at=excluded.updated_at,revoked_at=NULL`).bind(campaignId,String(profile.user_id||profile.id||''),String(profile.username||''),encrypted,expiresAt||null,now,now).run()}
export async function getInstagramConnection(db,campaignId,secret){await ensureInstagramTables(db);const row=await db.prepare('SELECT * FROM campaign_instagram_connections WHERE campaign_id=? AND revoked_at IS NULL LIMIT 1').bind(campaignId).first();return row?{token:await decryptToken(row.access_token_encrypted,secret),username:row.username,expiresAt:row.token_expires_at}:null}
export async function instagramConnectionStatus(db,campaignId){await ensureInstagramTables(db);const row=await db.prepare('SELECT instagram_user_id,username,token_expires_at,connected_at,updated_at,revoked_at FROM campaign_instagram_connections WHERE campaign_id=? LIMIT 1').bind(campaignId).first();return row?{connected:!row.revoked_at,userId:row.instagram_user_id,username:row.username,expiresAt:row.token_expires_at,connectedAt:row.connected_at,updatedAt:row.updated_at}:{connected:false}}
async function encryptToken(token,secret){if(!secret)throw new Error('INSTAGRAM_TOKEN_ENCRYPTION_KEY is required');const key=await crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',encoder.encode(secret)),'AES-GCM',false,['encrypt']),iv=crypto.getRandomValues(new Uint8Array(12)),bytes=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,encoder.encode(token)));return`${toBase64(iv)}.${toBase64(bytes)}`}
async function decryptToken(value,secret){if(!secret)throw new Error('INSTAGRAM_TOKEN_ENCRYPTION_KEY is required');const[ivPart,bodyPart]=String(value||'').split('.'),key=await crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',encoder.encode(secret)),'AES-GCM',false,['decrypt']);return decoder.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:fromBase64(ivPart)},key,fromBase64(bodyPart)))}
function randomSecret(size){return toBase64(crypto.getRandomValues(new Uint8Array(size))).replace(/[+/=]/g,c=>({'+':'-','/':'_','=':''}[c]))}async function sha256(value){return[...new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(String(value||''))))].map(b=>b.toString(16).padStart(2,'0')).join('')}function toBase64(bytes){let value='';for(const byte of bytes)value+=String.fromCharCode(byte);return btoa(value)}function fromBase64(value){const raw=atob(value||'');return Uint8Array.from(raw,c=>c.charCodeAt(0))}
